//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

// Generated by Scripts/generate-grove-fhir-swift-contract.py. Do not edit by hand.
// Machine-generated inventory rows and claim facts intentionally bypass style lint.
// swiftlint:disable all

#if canImport(HealthKit)

import GroveFHIRContract
public import HealthKit
import ModelsR4



/// Every source type in the HealthKit adapter inventory, generated from healthkit-adapter.json.
public enum HealthKitSourceType: String, CaseIterable, Sendable {
    case abdominalCramps = "HKCategoryTypeIdentifierAbdominalCramps"
    case acne = "HKCategoryTypeIdentifierAcne"
    case appetiteChanges = "HKCategoryTypeIdentifierAppetiteChanges"
    case appleStandHour = "HKCategoryTypeIdentifierAppleStandHour"
    case appleWalkingSteadinessEvent = "HKCategoryTypeIdentifierAppleWalkingSteadinessEvent"
    case audioExposureEvent = "HKCategoryTypeIdentifierAudioExposureEvent"
    case bladderIncontinence = "HKCategoryTypeIdentifierBladderIncontinence"
    case bleedingAfterPregnancy = "HKCategoryTypeIdentifierBleedingAfterPregnancy"
    case bleedingDuringPregnancy = "HKCategoryTypeIdentifierBleedingDuringPregnancy"
    case bloating = "HKCategoryTypeIdentifierBloating"
    case breastPain = "HKCategoryTypeIdentifierBreastPain"
    case cervicalMucusQuality = "HKCategoryTypeIdentifierCervicalMucusQuality"
    case chestTightnessOrPain = "HKCategoryTypeIdentifierChestTightnessOrPain"
    case chills = "HKCategoryTypeIdentifierChills"
    case constipation = "HKCategoryTypeIdentifierConstipation"
    case contraceptive = "HKCategoryTypeIdentifierContraceptive"
    case coughing = "HKCategoryTypeIdentifierCoughing"
    case diarrhea = "HKCategoryTypeIdentifierDiarrhea"
    case dizziness = "HKCategoryTypeIdentifierDizziness"
    case drySkin = "HKCategoryTypeIdentifierDrySkin"
    case fainting = "HKCategoryTypeIdentifierFainting"
    case fatigue = "HKCategoryTypeIdentifierFatigue"
    case fever = "HKCategoryTypeIdentifierFever"
    case generalizedBodyAche = "HKCategoryTypeIdentifierGeneralizedBodyAche"
    case hairLoss = "HKCategoryTypeIdentifierHairLoss"
    case handwashingEvent = "HKCategoryTypeIdentifierHandwashingEvent"
    case headache = "HKCategoryTypeIdentifierHeadache"
    case headphoneAudioExposureEvent = "HKCategoryTypeIdentifierHeadphoneAudioExposureEvent"
    case heartburn = "HKCategoryTypeIdentifierHeartburn"
    case highHeartRateEvent = "HKCategoryTypeIdentifierHighHeartRateEvent"
    case hotFlashes = "HKCategoryTypeIdentifierHotFlashes"
    case hypertensionEvent = "HKCategoryTypeIdentifierHypertensionEvent"
    case infrequentMenstrualCycles = "HKCategoryTypeIdentifierInfrequentMenstrualCycles"
    case intermenstrualBleeding = "HKCategoryTypeIdentifierIntermenstrualBleeding"
    case irregularHeartRhythmEvent = "HKCategoryTypeIdentifierIrregularHeartRhythmEvent"
    case irregularMenstrualCycles = "HKCategoryTypeIdentifierIrregularMenstrualCycles"
    case lactation = "HKCategoryTypeIdentifierLactation"
    case lossOfSmell = "HKCategoryTypeIdentifierLossOfSmell"
    case lossOfTaste = "HKCategoryTypeIdentifierLossOfTaste"
    case lowCardioFitnessEvent = "HKCategoryTypeIdentifierLowCardioFitnessEvent"
    case lowHeartRateEvent = "HKCategoryTypeIdentifierLowHeartRateEvent"
    case lowerBackPain = "HKCategoryTypeIdentifierLowerBackPain"
    case memoryLapse = "HKCategoryTypeIdentifierMemoryLapse"
    case menstrualFlow = "HKCategoryTypeIdentifierMenstrualFlow"
    case mindfulSession = "HKCategoryTypeIdentifierMindfulSession"
    case moodChanges = "HKCategoryTypeIdentifierMoodChanges"
    case nausea = "HKCategoryTypeIdentifierNausea"
    case nightSweats = "HKCategoryTypeIdentifierNightSweats"
    case ovulationTestResult = "HKCategoryTypeIdentifierOvulationTestResult"
    case pelvicPain = "HKCategoryTypeIdentifierPelvicPain"
    case persistentIntermenstrualBleeding = "HKCategoryTypeIdentifierPersistentIntermenstrualBleeding"
    case pregnancy = "HKCategoryTypeIdentifierPregnancy"
    case pregnancyTestResult = "HKCategoryTypeIdentifierPregnancyTestResult"
    case progesteroneTestResult = "HKCategoryTypeIdentifierProgesteroneTestResult"
    case prolongedMenstrualPeriods = "HKCategoryTypeIdentifierProlongedMenstrualPeriods"
    case rapidPoundingOrFlutteringHeartbeat = "HKCategoryTypeIdentifierRapidPoundingOrFlutteringHeartbeat"
    case runnyNose = "HKCategoryTypeIdentifierRunnyNose"
    case sexualActivity = "HKCategoryTypeIdentifierSexualActivity"
    case shortnessOfBreath = "HKCategoryTypeIdentifierShortnessOfBreath"
    case sinusCongestion = "HKCategoryTypeIdentifierSinusCongestion"
    case skippedHeartbeat = "HKCategoryTypeIdentifierSkippedHeartbeat"
    case sleepAnalysis = "HKCategoryTypeIdentifierSleepAnalysis"
    case sleepApneaEvent = "HKCategoryTypeIdentifierSleepApneaEvent"
    case sleepChanges = "HKCategoryTypeIdentifierSleepChanges"
    case soreThroat = "HKCategoryTypeIdentifierSoreThroat"
    case toothbrushingEvent = "HKCategoryTypeIdentifierToothbrushingEvent"
    case vaginalDryness = "HKCategoryTypeIdentifierVaginalDryness"
    case vomiting = "HKCategoryTypeIdentifierVomiting"
    case wheezing = "HKCategoryTypeIdentifierWheezing"
    case activityMoveMode = "HKCharacteristicTypeIdentifierActivityMoveMode"
    case biologicalSex = "HKCharacteristicTypeIdentifierBiologicalSex"
    case bloodType = "HKCharacteristicTypeIdentifierBloodType"
    case dateOfBirth = "HKCharacteristicTypeIdentifierDateOfBirth"
    case fitzpatrickSkinType = "HKCharacteristicTypeIdentifierFitzpatrickSkinType"
    case wheelchairUse = "HKCharacteristicTypeIdentifierWheelchairUse"
    case allergyRecord = "HKClinicalTypeIdentifierAllergyRecord"
    case clinicalNoteRecord = "HKClinicalTypeIdentifierClinicalNoteRecord"
    case conditionRecord = "HKClinicalTypeIdentifierConditionRecord"
    case coverageRecord = "HKClinicalTypeIdentifierCoverageRecord"
    case immunizationRecord = "HKClinicalTypeIdentifierImmunizationRecord"
    case labResultRecord = "HKClinicalTypeIdentifierLabResultRecord"
    case medicationRecord = "HKClinicalTypeIdentifierMedicationRecord"
    case procedureRecord = "HKClinicalTypeIdentifierProcedureRecord"
    case vitalSignRecord = "HKClinicalTypeIdentifierVitalSignRecord"
    case bloodPressure = "HKCorrelationTypeIdentifierBloodPressure"
    case food = "HKCorrelationTypeIdentifierFood"
    case audiogram = "HKDataTypeIdentifierAudiogram"
    case electrocardiogram = "HKDataTypeIdentifierElectrocardiogram"
    case heartbeatSeries = "HKDataTypeIdentifierHeartbeatSeries"
    case stateOfMind = "HKDataTypeStateOfMind"
    case userAnnotatedMedicationConcept = "HKDataTypeUserAnnotatedMedicationConcept"
    case cda = "HKDocumentTypeIdentifierCDA"
    case medicationDoseEvent = "HKMedicationDoseEventTypeIdentifierMedicationDoseEvent"
    case activeEnergyBurned = "HKQuantityTypeIdentifierActiveEnergyBurned"
    case appleExerciseTime = "HKQuantityTypeIdentifierAppleExerciseTime"
    case appleMoveTime = "HKQuantityTypeIdentifierAppleMoveTime"
    case appleSleepingBreathingDisturbances = "HKQuantityTypeIdentifierAppleSleepingBreathingDisturbances"
    case appleSleepingWristTemperature = "HKQuantityTypeIdentifierAppleSleepingWristTemperature"
    case appleStandTime = "HKQuantityTypeIdentifierAppleStandTime"
    case appleWalkingSteadiness = "HKQuantityTypeIdentifierAppleWalkingSteadiness"
    case atrialFibrillationBurden = "HKQuantityTypeIdentifierAtrialFibrillationBurden"
    case basalBodyTemperature = "HKQuantityTypeIdentifierBasalBodyTemperature"
    case basalEnergyBurned = "HKQuantityTypeIdentifierBasalEnergyBurned"
    case bloodAlcoholContent = "HKQuantityTypeIdentifierBloodAlcoholContent"
    case bloodGlucose = "HKQuantityTypeIdentifierBloodGlucose"
    case bloodPressureDiastolic = "HKQuantityTypeIdentifierBloodPressureDiastolic"
    case bloodPressureSystolic = "HKQuantityTypeIdentifierBloodPressureSystolic"
    case bodyFatPercentage = "HKQuantityTypeIdentifierBodyFatPercentage"
    case bodyMass = "HKQuantityTypeIdentifierBodyMass"
    case bodyMassIndex = "HKQuantityTypeIdentifierBodyMassIndex"
    case bodyTemperature = "HKQuantityTypeIdentifierBodyTemperature"
    case crossCountrySkiingSpeed = "HKQuantityTypeIdentifierCrossCountrySkiingSpeed"
    case cyclingCadence = "HKQuantityTypeIdentifierCyclingCadence"
    case cyclingFunctionalThresholdPower = "HKQuantityTypeIdentifierCyclingFunctionalThresholdPower"
    case cyclingPower = "HKQuantityTypeIdentifierCyclingPower"
    case cyclingSpeed = "HKQuantityTypeIdentifierCyclingSpeed"
    case dietaryBiotin = "HKQuantityTypeIdentifierDietaryBiotin"
    case dietaryCaffeine = "HKQuantityTypeIdentifierDietaryCaffeine"
    case dietaryCalcium = "HKQuantityTypeIdentifierDietaryCalcium"
    case dietaryCarbohydrates = "HKQuantityTypeIdentifierDietaryCarbohydrates"
    case dietaryChloride = "HKQuantityTypeIdentifierDietaryChloride"
    case dietaryCholesterol = "HKQuantityTypeIdentifierDietaryCholesterol"
    case dietaryChromium = "HKQuantityTypeIdentifierDietaryChromium"
    case dietaryCopper = "HKQuantityTypeIdentifierDietaryCopper"
    case dietaryEnergyConsumed = "HKQuantityTypeIdentifierDietaryEnergyConsumed"
    case dietaryFatMonounsaturated = "HKQuantityTypeIdentifierDietaryFatMonounsaturated"
    case dietaryFatPolyunsaturated = "HKQuantityTypeIdentifierDietaryFatPolyunsaturated"
    case dietaryFatSaturated = "HKQuantityTypeIdentifierDietaryFatSaturated"
    case dietaryFatTotal = "HKQuantityTypeIdentifierDietaryFatTotal"
    case dietaryFiber = "HKQuantityTypeIdentifierDietaryFiber"
    case dietaryFolate = "HKQuantityTypeIdentifierDietaryFolate"
    case dietaryIodine = "HKQuantityTypeIdentifierDietaryIodine"
    case dietaryIron = "HKQuantityTypeIdentifierDietaryIron"
    case dietaryMagnesium = "HKQuantityTypeIdentifierDietaryMagnesium"
    case dietaryManganese = "HKQuantityTypeIdentifierDietaryManganese"
    case dietaryMolybdenum = "HKQuantityTypeIdentifierDietaryMolybdenum"
    case dietaryNiacin = "HKQuantityTypeIdentifierDietaryNiacin"
    case dietaryPantothenicAcid = "HKQuantityTypeIdentifierDietaryPantothenicAcid"
    case dietaryPhosphorus = "HKQuantityTypeIdentifierDietaryPhosphorus"
    case dietaryPotassium = "HKQuantityTypeIdentifierDietaryPotassium"
    case dietaryProtein = "HKQuantityTypeIdentifierDietaryProtein"
    case dietaryRiboflavin = "HKQuantityTypeIdentifierDietaryRiboflavin"
    case dietarySelenium = "HKQuantityTypeIdentifierDietarySelenium"
    case dietarySodium = "HKQuantityTypeIdentifierDietarySodium"
    case dietarySugar = "HKQuantityTypeIdentifierDietarySugar"
    case dietaryThiamin = "HKQuantityTypeIdentifierDietaryThiamin"
    case dietaryVitaminA = "HKQuantityTypeIdentifierDietaryVitaminA"
    case dietaryVitaminB12 = "HKQuantityTypeIdentifierDietaryVitaminB12"
    case dietaryVitaminB6 = "HKQuantityTypeIdentifierDietaryVitaminB6"
    case dietaryVitaminC = "HKQuantityTypeIdentifierDietaryVitaminC"
    case dietaryVitaminD = "HKQuantityTypeIdentifierDietaryVitaminD"
    case dietaryVitaminE = "HKQuantityTypeIdentifierDietaryVitaminE"
    case dietaryVitaminK = "HKQuantityTypeIdentifierDietaryVitaminK"
    case dietaryWater = "HKQuantityTypeIdentifierDietaryWater"
    case dietaryZinc = "HKQuantityTypeIdentifierDietaryZinc"
    case distanceCrossCountrySkiing = "HKQuantityTypeIdentifierDistanceCrossCountrySkiing"
    case distanceCycling = "HKQuantityTypeIdentifierDistanceCycling"
    case distanceDownhillSnowSports = "HKQuantityTypeIdentifierDistanceDownhillSnowSports"
    case distancePaddleSports = "HKQuantityTypeIdentifierDistancePaddleSports"
    case distanceRowing = "HKQuantityTypeIdentifierDistanceRowing"
    case distanceSkatingSports = "HKQuantityTypeIdentifierDistanceSkatingSports"
    case distanceSwimming = "HKQuantityTypeIdentifierDistanceSwimming"
    case distanceWalkingRunning = "HKQuantityTypeIdentifierDistanceWalkingRunning"
    case distanceWheelchair = "HKQuantityTypeIdentifierDistanceWheelchair"
    case electrodermalActivity = "HKQuantityTypeIdentifierElectrodermalActivity"
    case environmentalAudioExposure = "HKQuantityTypeIdentifierEnvironmentalAudioExposure"
    case environmentalSoundReduction = "HKQuantityTypeIdentifierEnvironmentalSoundReduction"
    case estimatedWorkoutEffortScore = "HKQuantityTypeIdentifierEstimatedWorkoutEffortScore"
    case flightsClimbed = "HKQuantityTypeIdentifierFlightsClimbed"
    case forcedExpiratoryVolume1 = "HKQuantityTypeIdentifierForcedExpiratoryVolume1"
    case forcedVitalCapacity = "HKQuantityTypeIdentifierForcedVitalCapacity"
    case headphoneAudioExposure = "HKQuantityTypeIdentifierHeadphoneAudioExposure"
    case heartRate = "HKQuantityTypeIdentifierHeartRate"
    case heartRateRecoveryOneMinute = "HKQuantityTypeIdentifierHeartRateRecoveryOneMinute"
    case heartRateVariabilitySDNN = "HKQuantityTypeIdentifierHeartRateVariabilitySDNN"
    case height = "HKQuantityTypeIdentifierHeight"
    case inhalerUsage = "HKQuantityTypeIdentifierInhalerUsage"
    case insulinDelivery = "HKQuantityTypeIdentifierInsulinDelivery"
    case leanBodyMass = "HKQuantityTypeIdentifierLeanBodyMass"
    case nikeFuel = "HKQuantityTypeIdentifierNikeFuel"
    case numberOfAlcoholicBeverages = "HKQuantityTypeIdentifierNumberOfAlcoholicBeverages"
    case numberOfTimesFallen = "HKQuantityTypeIdentifierNumberOfTimesFallen"
    case oxygenSaturation = "HKQuantityTypeIdentifierOxygenSaturation"
    case paddleSportsSpeed = "HKQuantityTypeIdentifierPaddleSportsSpeed"
    case peakExpiratoryFlowRate = "HKQuantityTypeIdentifierPeakExpiratoryFlowRate"
    case peripheralPerfusionIndex = "HKQuantityTypeIdentifierPeripheralPerfusionIndex"
    case physicalEffort = "HKQuantityTypeIdentifierPhysicalEffort"
    case pushCount = "HKQuantityTypeIdentifierPushCount"
    case respiratoryRate = "HKQuantityTypeIdentifierRespiratoryRate"
    case restingHeartRate = "HKQuantityTypeIdentifierRestingHeartRate"
    case rowingSpeed = "HKQuantityTypeIdentifierRowingSpeed"
    case runningGroundContactTime = "HKQuantityTypeIdentifierRunningGroundContactTime"
    case runningPower = "HKQuantityTypeIdentifierRunningPower"
    case runningSpeed = "HKQuantityTypeIdentifierRunningSpeed"
    case runningStrideLength = "HKQuantityTypeIdentifierRunningStrideLength"
    case runningVerticalOscillation = "HKQuantityTypeIdentifierRunningVerticalOscillation"
    case sixMinuteWalkTestDistance = "HKQuantityTypeIdentifierSixMinuteWalkTestDistance"
    case stairAscentSpeed = "HKQuantityTypeIdentifierStairAscentSpeed"
    case stairDescentSpeed = "HKQuantityTypeIdentifierStairDescentSpeed"
    case stepCount = "HKQuantityTypeIdentifierStepCount"
    case swimmingStrokeCount = "HKQuantityTypeIdentifierSwimmingStrokeCount"
    case timeInDaylight = "HKQuantityTypeIdentifierTimeInDaylight"
    case uvExposure = "HKQuantityTypeIdentifierUVExposure"
    case underwaterDepth = "HKQuantityTypeIdentifierUnderwaterDepth"
    case vo2Max = "HKQuantityTypeIdentifierVO2Max"
    case waistCircumference = "HKQuantityTypeIdentifierWaistCircumference"
    case walkingAsymmetryPercentage = "HKQuantityTypeIdentifierWalkingAsymmetryPercentage"
    case walkingDoubleSupportPercentage = "HKQuantityTypeIdentifierWalkingDoubleSupportPercentage"
    case walkingHeartRateAverage = "HKQuantityTypeIdentifierWalkingHeartRateAverage"
    case walkingSpeed = "HKQuantityTypeIdentifierWalkingSpeed"
    case walkingStepLength = "HKQuantityTypeIdentifierWalkingStepLength"
    case waterTemperature = "HKQuantityTypeIdentifierWaterTemperature"
    case workoutEffortScore = "HKQuantityTypeIdentifierWorkoutEffortScore"
    case gad7 = "HKScoredAssessmentTypeIdentifierGAD7"
    case phq9 = "HKScoredAssessmentTypeIdentifierPHQ9"
    case visionPrescription = "HKVisionPrescriptionTypeIdentifier"
    case workoutRoute = "HKWorkoutRouteTypeIdentifier"
    case workout = "HKWorkoutTypeIdentifier"

    /// The inventory row of a sample's type, or `nil` for a type the inventory does not list.
    public init?(_ sample: HKSample) {
        self.init(rawValue: sample.sampleType.identifier)
    }
}


/// The guide's display of each code a HealthKit row's measurement states without one, generated from the
/// guide's LOINC concept catalog (terminology/loinc-concepts.json) and keyed by the code exactly as the
/// measurement states it.
enum HealthKitTerminology {
    /// The display of each such code.
    static let displays: [CodingContract: String] = [
        CodingContract(system: "http://loinc.org", code: "103208-5"): "Distance traveled",
        CodingContract(system: "http://loinc.org", code: "2708-6"): "Oxygen saturation in Arterial blood",
        CodingContract(system: "http://loinc.org", code: "29463-7"): "Body weight",
        CodingContract(system: "http://loinc.org", code: "39156-5"): "Body mass index (BMI) [Ratio]",
        CodingContract(system: "http://loinc.org", code: "8302-2"): "Body height",
        CodingContract(system: "http://loinc.org", code: "8310-5"): "Body temperature",
        CodingContract(system: "http://loinc.org", code: "85354-9"): "Blood pressure panel with all children optional",
        CodingContract(system: "http://loinc.org", code: "8867-4"): "Heart rate",
        CodingContract(system: "http://loinc.org", code: "9279-1"): "Respiratory rate",
    ]
}


/// The HealthKit electrocardiogram claim, generated from healthkit-adapter.json sensorAdapterClaims and
/// typed against the HealthKit SDK, so the compiler checks the guide's spelling of every HealthKit value.
@available(iOS 18, macOS 15, watchOS 11, *)
enum HealthKitElectrocardiogramClaim {
    /// One output the claim declares.
    struct Output: Sendable {
        /// The output role.
        let role: String
        /// The output discriminator.
        let discriminator: String
        /// The output's exact direct `meta.profile` claim.
        let profiles: [FHIRPrimitive<Canonical>]
    }

    /// The waveform Observation.
    static let waveform = Output(
        role: "electrocardiogram",
        discriminator: "single",
        profiles: HealthKitContract.electrocardiogramProfiles
    )
    /// The waveform's code: the code of the sensor contract its first profile is, with the guide's display.
    static let waveformCode = CodingContract(system: "http://loinc.org", code: "11524-6", display: "EKG study")
    /// The average-heart-rate Observation, derived from the waveform.
    static let averageHeartRate = Output(
        role: "average-heart-rate",
        discriminator: "single",
        profiles: [Profile.groveMobileHeartRate, Profile.healthkitEcgAverageHeartRateObservation]
    )
    /// The average heart rate's code, with the guide's display.
    static let averageHeartRateCode = CodingContract(system: "http://loinc.org", code: "8867-4", display: "Heart rate")
    /// The measurement whose code, category and quantity the average heart rate states (the claim's code
    /// adds the display). Its effective choice is not the claim's: the average heart rate always states
    /// the waveform's exact effectivePeriod.
    static let averageHeartRateMeasurement = MeasurementCatalog.heartRate
    /// The lead whose voltages the waveform carries.
    static let sourceLead = HKElectrocardiogram.Lead.appleWatchSimilarToLeadI
    /// The coding of that lead on the waveform component.
    static let leadCode = CodingContract(system: "urn:iso:std:iso:11073:10101", code: "131329", display: "MDC_ECG_ELEC_POTL_I")
    /// The unit of the waveform's voltages.
    static let voltageQuantity = QuantityContract(system: "http://unitsofmeasure.org", code: "mV", unit: "mV", valueDomain: nil)
    /// The CodeSystem of the Observation.interpretation code each HKElectrocardiogram.classification maps to.
    static let classificationSystem = "https://grovealliance.org/fhir/healthkit/CodeSystem/healthkit-ecg-classification"
    /// The Observation.interpretation code of each HKElectrocardiogram.classification the guide admits.
    static let classificationCodes: [HKElectrocardiogram.Classification: String] = [
        HKElectrocardiogram.Classification.notSet: "notSet",
        HKElectrocardiogram.Classification.sinusRhythm: "sinusRhythm",
        HKElectrocardiogram.Classification.atrialFibrillation: "atrialFibrillation",
        HKElectrocardiogram.Classification.inconclusiveLowHeartRate: "inconclusiveLowHeartRate",
        HKElectrocardiogram.Classification.inconclusiveHighHeartRate: "inconclusiveHighHeartRate",
        HKElectrocardiogram.Classification.inconclusivePoorReading: "inconclusivePoorReading",
        HKElectrocardiogram.Classification.inconclusiveOther: "inconclusiveOther",
        HKElectrocardiogram.Classification.unrecognized: "unrecognized",
    ]
    /// The CodeSystem of the healthkit-ecg-symptoms-status.valueCode code each HKElectrocardiogram.symptomsStatus maps to.
    static let symptomsStatusSystem = "https://grovealliance.org/fhir/healthkit/CodeSystem/healthkit-ecg-symptoms-status"
    /// The healthkit-ecg-symptoms-status.valueCode code of each HKElectrocardiogram.symptomsStatus the guide admits.
    static let symptomsStatusCodes: [HKElectrocardiogram.SymptomsStatus: String] = [
        HKElectrocardiogram.SymptomsStatus.notSet: "notSet",
        HKElectrocardiogram.SymptomsStatus.none: "none",
        HKElectrocardiogram.SymptomsStatus.present: "present",
    ]
    /// The CodeSystem of the Observation.method code each HKMetadataKeyAppleECGAlgorithmVersion maps to.
    static let algorithmVersionSystem = "https://grovealliance.org/fhir/healthkit/CodeSystem/healthkit-ecg-algorithm-version"
    /// The Observation.method code of each HKMetadataKeyAppleECGAlgorithmVersion the guide admits.
    static let algorithmVersionCodes: [Int: String] = [
        1: "version1",
        2: "version2",
    ]
    /// The symptom source types an ECG may reference through Observation.hasMember.
    static let correlatedSymptomSourceTypes: Set<HealthKitSourceType> = [
        .rapidPoundingOrFlutteringHeartbeat,
        .skippedHeartbeat,
        .fatigue,
        .shortnessOfBreath,
        .chestTightnessOrPain,
        .fainting,
        .dizziness,
    ]
}

#endif
