version: 1
builder:
  configs:
    - documentation_targets:
        - Grove
        - FHIRModelsExtensions
        - FHIRPathParser
        - FHIRQuestionnaires
        - ResearchKitOnFHIR
        - GroveTesting
        - XCTGrove
        - GroveAccessGuard
        - GroveAccount
        - XCTGroveAccount
        - GroveAccountPhoneNumbers
        - GroveBluetoothServices
        - GroveBluetooth
        - GroveChat
        - GroveConsent
        - GroveContact
        - GroveDevices
        - GroveDevicesUI
        - GroveOmron
        - GroveFHIR
        - GroveFHIRMockPatients
        - EDFFormat
        - GroveFirebaseAccount
        - GroveFirebaseConfiguration
        - GroveFirestore
        - GroveFirebaseStorage
        - GroveFirebaseAccountStorage
        - GroveFoundation
        - GroveLocalization
        - ThreadLocal
        - GroveHealthKit
        - GroveHealthKitBulkExport
        - GroveHealthKitFHIR
        - GroveHealthKitUI
        - GroveLLM
        - GroveLLMLocal
        - GroveLLMLocalDownload
        - GroveLLMOpenAI
        - GroveLLMOpenAIRealtime
        - GroveLLMAnthropic
        - GroveLLMGemini
        - GroveLicense
        - GroveLocation
        - ByteCoding
        - GroveNumerics
        - XCTByteCoding
        - ByteCodingTesting
        - GroveNotifications
        - XCTGroveNotifications
        - XCTGroveNotificationsUI
        - GroveOnboarding
        - GroveQuestionnaire
        - GroveQuestionnaireCatalog
        - GroveQuestionnaireFHIR
        - GroveQuestionnaireLegacy
        - XCTGroveQuestionnaire
        - GroveScheduler
        - GroveSensorKit
        - GroveSpeechRecognizer
        - GroveSpeechSynthesizer
        - GroveLocalStorage
        - GroveKeychainStorage
        - GroveStudyDefinition
        - GroveViews
        - GrovePersonalInfo
        - GroveValidation
        - XCTHealthKit
        - RuntimeAssertions
        - RuntimeAssertionsTesting
        - XCTestApp
        - XCTestExtensions
        - GroveSchedulerUI
        - GroveStudy
