version: 1
builder:
  configs:
    - documentation_targets:
        - Spezi
        - FHIRModelsExtensions
        - FHIRPathParser
        - FHIRQuestionnaires
        - HealthKitOnFHIR
        - ResearchKitOnFHIR
        - SpeziTesting
        - XCTSpezi
        - SpeziAccessGuard
        - SpeziAccount
        - XCTSpeziAccount
        - SpeziAccountPhoneNumbers
        - SpeziBluetoothServices
        - SpeziBluetooth
        - SpeziChat
        - SpeziConsent
        - SpeziContact
        - SpeziDevices
        - SpeziDevicesUI
        - SpeziOmron
        - SpeziFHIR
        - SpeziFHIRHealthKit
        - SpeziFHIRMockPatients
        - EDFFormat
        - SpeziFirebaseAccount
        - SpeziFirebaseConfiguration
        - SpeziFirestore
        - SpeziFirebaseStorage
        - SpeziFirebaseAccountStorage
        - SpeziFoundation
        - SpeziLocalization
        - ThreadLocal
        - SpeziHealthKit
        - SpeziHealthKitBulkExport
        - SpeziHealthKitUI
        - SpeziLLM
        - SpeziLLMLocal
        - SpeziLLMLocalDownload
        - SpeziLLMOpenAI
        - SpeziLLMFog
        - SpeziLLMOpenAIRealtime
        - SpeziLLMAnthropic
        - SpeziLLMGemini
        - SpeziLicense
        - SpeziLocation
        - ByteCoding
        - SpeziNumerics
        - XCTByteCoding
        - ByteCodingTesting
        - SpeziNotifications
        - XCTSpeziNotifications
        - XCTSpeziNotificationsUI
        - SpeziOnboarding
        - SpeziQuestionnaire
        - SpeziQuestionnaireCatalog
        - SpeziQuestionnaireFHIR
        - XCTSpeziQuestionnaire
        - SpeziScheduler
        - SpeziSensorKit
        - SpeziSpeechRecognizer
        - SpeziSpeechSynthesizer
        - SpeziLocalStorage
        - SpeziKeychainStorage
        - SpeziStudyDefinition
        - SpeziViews
        - SpeziPersonalInfo
        - SpeziValidation
        - XCTHealthKit
        - RuntimeAssertions
        - RuntimeAssertionsTesting
        - XCTestApp
        - XCTestExtensions
        - SpeziSchedulerUI
        - SpeziStudy
