//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

// Generated by Scripts/generate-grove-fhir-semantic-vector-fixtures.py. Do not edit by hand.

struct MobileSemanticVectorFixture: Sendable {
    enum Effective: Sendable {
        case dateTime(String)
        case period(start: String, end: String)
    }

    struct Component: Sendable {
        let id: String
        let system: String
        let code: String
        let value: Double
        let quantitySystem: String
        let quantityCode: String
        let unit: String
    }

    enum Result: Sendable {
        case quantity(value: Double, system: String, code: String, unit: String)
        case components([Component])
        case codeableConcept(system: String, code: String)
    }

    let id: String
    let profile: String
    let codeSystem: String
    let code: String
    let effective: Effective
    let result: Result
}


enum MobileSemanticVectorFixtures {
    static let all: [MobileSemanticVectorFixture] = [
        MobileSemanticVectorFixture(
            id: "active-energy",
            profile: "https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-active-energy",
            codeSystem: "https://grovealliance.org/fhir/mobile/CodeSystem/grove-mobile-measurement",
            code: "active-energy-burned",
            effective: .period(start: "2026-08-20T08:00:00-07:00", end: "2026-08-20T09:00:00-07:00"),
            result: .quantity(value: 312.5, system: "http://unitsofmeasure.org", code: "kcal", unit: "kcal")
        ),
        MobileSemanticVectorFixture(
            id: "basal-body-temperature",
            profile: "https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-basal-body-temperature",
            codeSystem: "https://grovealliance.org/fhir/mobile/CodeSystem/grove-mobile-measurement",
            code: "basal-body-temperature",
            effective: .dateTime("2026-08-20T06:45:00-07:00"),
            result: .quantity(value: 36.52, system: "http://unitsofmeasure.org", code: "Cel", unit: "Cel")
        ),
        MobileSemanticVectorFixture(
            id: "blood-pressure",
            profile: "https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-blood-pressure",
            codeSystem: "http://loinc.org",
            code: "85354-9",
            effective: .dateTime("2026-08-20T08:10:00-07:00"),
            result: .components([
                .init(id: "systolic", system: "http://loinc.org", code: "8480-6", value: 118, quantitySystem: "http://unitsofmeasure.org", quantityCode: "mm[Hg]", unit: "mmHg"),
                .init(id: "diastolic", system: "http://loinc.org", code: "8462-4", value: 76, quantitySystem: "http://unitsofmeasure.org", quantityCode: "mm[Hg]", unit: "mmHg")
            ])
        ),
        MobileSemanticVectorFixture(
            id: "body-height",
            profile: "https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-body-height",
            codeSystem: "http://loinc.org",
            code: "8302-2",
            effective: .dateTime("2026-08-20T08:15:00-07:00"),
            result: .quantity(value: 171.2, system: "http://unitsofmeasure.org", code: "cm", unit: "cm")
        ),
        MobileSemanticVectorFixture(
            id: "body-temperature",
            profile: "https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-body-temperature",
            codeSystem: "http://loinc.org",
            code: "8310-5",
            effective: .dateTime("2026-08-20T08:20:00-07:00"),
            result: .quantity(value: 37.1, system: "http://unitsofmeasure.org", code: "Cel", unit: "Cel")
        ),
        MobileSemanticVectorFixture(
            id: "body-weight",
            profile: "https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-body-weight",
            codeSystem: "http://loinc.org",
            code: "29463-7",
            effective: .dateTime("2026-08-20T08:25:00-07:00"),
            result: .quantity(value: 68.4, system: "http://unitsofmeasure.org", code: "kg", unit: "kg")
        ),
        MobileSemanticVectorFixture(
            id: "distance",
            profile: "https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-distance",
            codeSystem: "http://loinc.org",
            code: "103208-5",
            effective: .period(start: "2026-08-20T07:00:00-07:00", end: "2026-08-20T07:30:00-07:00"),
            result: .quantity(value: 4820.5, system: "http://unitsofmeasure.org", code: "m", unit: "m")
        ),
        MobileSemanticVectorFixture(
            id: "heart-rate",
            profile: "https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-heart-rate",
            codeSystem: "http://loinc.org",
            code: "8867-4",
            effective: .dateTime("2026-08-20T08:30:00.251-07:00"),
            result: .quantity(value: 72, system: "http://unitsofmeasure.org", code: "/min", unit: "beats/minute")
        ),
        MobileSemanticVectorFixture(
            id: "oxygen-saturation",
            profile: "https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-oxygen-saturation",
            codeSystem: "http://loinc.org",
            code: "2708-6",
            effective: .dateTime("2026-08-20T08:35:00-07:00"),
            result: .quantity(value: 98, system: "http://unitsofmeasure.org", code: "%", unit: "%")
        ),
        MobileSemanticVectorFixture(
            id: "respiratory-rate",
            profile: "https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-respiratory-rate",
            codeSystem: "http://loinc.org",
            code: "9279-1",
            effective: .dateTime("2026-08-20T08:40:00-07:00"),
            result: .quantity(value: 15, system: "http://unitsofmeasure.org", code: "/min", unit: "breaths/minute")
        ),
        MobileSemanticVectorFixture(
            id: "sleep-duration",
            profile: "https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-sleep-duration",
            codeSystem: "http://loinc.org",
            code: "93832-4",
            effective: .period(start: "2026-08-19T23:00:00-07:00", end: "2026-08-20T06:30:00-07:00"),
            result: .quantity(value: 7.5, system: "http://unitsofmeasure.org", code: "h", unit: "h")
        ),
        MobileSemanticVectorFixture(
            id: "sleep-stage",
            profile: "https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-sleep-stage",
            codeSystem: "https://grovealliance.org/fhir/mobile/CodeSystem/grove-mobile-measurement",
            code: "sleep-stage",
            effective: .period(start: "2026-08-20T00:10:00-07:00", end: "2026-08-20T00:42:00-07:00"),
            result: .codeableConcept(system: "https://grovealliance.org/fhir/mobile/CodeSystem/grove-sleep-stage", code: "light")
        ),
        MobileSemanticVectorFixture(
            id: "step-count",
            profile: "https://grovealliance.org/fhir/mobile/StructureDefinition/grove-mobile-step-count",
            codeSystem: "https://grovealliance.org/fhir/mobile/CodeSystem/grove-mobile-measurement",
            code: "step-count-total",
            effective: .period(start: "2026-08-20T08:00:00-07:00", end: "2026-08-20T09:00:00-07:00"),
            result: .quantity(value: 1042, system: "http://unitsofmeasure.org", code: "{steps}", unit: "steps")
        )
    ]
}
