//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

// Generated by Scripts/generate-grove-fhir-semantic-vector-fixtures.py. Do not edit by hand.

struct MobileSemanticVectorFixture: Sendable {
    enum Effective: Sendable {
        case dateTime(String)
        case period(start: String, end: String)
    }

    struct Component: Sendable {
        let id: String
        let value: Double
    }

    enum Result: Sendable {
        case quantity(value: Double)
        case components([Component])
        case codeableConcept(code: String)
    }

    let id: String
    let effective: Effective
    let result: Result
}


enum MobileSemanticVectorFixtures {
    static let all: [MobileSemanticVectorFixture] = [
        MobileSemanticVectorFixture(
            id: "active-energy",
            effective: .period(start: "2026-08-20T08:00:00-07:00", end: "2026-08-20T09:00:00-07:00"),
            result: .quantity(value: 312.5)
        ),
        MobileSemanticVectorFixture(
            id: "basal-body-temperature",
            effective: .dateTime("2026-08-20T06:45:00-07:00"),
            result: .quantity(value: 36.52)
        ),
        MobileSemanticVectorFixture(
            id: "blood-pressure",
            effective: .dateTime("2026-08-20T08:10:00-07:00"),
            result: .components([
                .init(id: "systolic", value: 118),
                .init(id: "diastolic", value: 76)
            ])
        ),
        MobileSemanticVectorFixture(
            id: "body-height",
            effective: .dateTime("2026-08-20T08:15:00-07:00"),
            result: .quantity(value: 171.2)
        ),
        MobileSemanticVectorFixture(
            id: "body-temperature",
            effective: .dateTime("2026-08-20T08:20:00-07:00"),
            result: .quantity(value: 37.1)
        ),
        MobileSemanticVectorFixture(
            id: "body-weight",
            effective: .dateTime("2026-08-20T08:25:00-07:00"),
            result: .quantity(value: 68.4)
        ),
        MobileSemanticVectorFixture(
            id: "distance",
            effective: .period(start: "2026-08-20T07:00:00-07:00", end: "2026-08-20T07:30:00-07:00"),
            result: .quantity(value: 4820.5)
        ),
        MobileSemanticVectorFixture(
            id: "heart-rate",
            effective: .dateTime("2026-08-20T08:30:00.251-07:00"),
            result: .quantity(value: 72)
        ),
        MobileSemanticVectorFixture(
            id: "oxygen-saturation",
            effective: .dateTime("2026-08-20T08:35:00-07:00"),
            result: .quantity(value: 98)
        ),
        MobileSemanticVectorFixture(
            id: "respiratory-rate",
            effective: .dateTime("2026-08-20T08:40:00-07:00"),
            result: .quantity(value: 15)
        ),
        MobileSemanticVectorFixture(
            id: "sleep-duration",
            effective: .period(start: "2026-08-19T23:00:00-07:00", end: "2026-08-20T06:30:00-07:00"),
            result: .quantity(value: 7.5)
        ),
        MobileSemanticVectorFixture(
            id: "sleep-stage",
            effective: .period(start: "2026-08-20T00:10:00-07:00", end: "2026-08-20T00:42:00-07:00"),
            result: .codeableConcept(code: "light")
        ),
        MobileSemanticVectorFixture(
            id: "step-count",
            effective: .period(start: "2026-08-20T08:00:00-07:00", end: "2026-08-20T09:00:00-07:00"),
            result: .quantity(value: 1042)
        )
    ]
}
