//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

// Generated by Scripts/generate-grove-sensor-swift-contract.py. Do not edit by hand.

// swiftlint:disable all

/// The producer-side assertion that admits an opaque native sensor payload.
/// Grove consumes this value during preflight and never serializes it into FHIR.
public enum GroveSensorRawPayloadAdmission: String, CaseIterable, Hashable, Sendable {
    /// The caller explicitly authorizes disclosure of exact opaque bytes; Grove does not inspect or sanitize them.
    case callerAuthorizedOpaquePayload = "caller-authorized-opaque-payload"
    /// The producer independently verified that the supplied bytes are sanitized.
    case verifiedSanitizedInput = "verified-sanitized-input"
}


/// Generated canonical and identity constants for the SensorKit v0.2 producer.
public enum GroveSensorKitContract {
    public static let canonicalRoot = "https://grovealliance.org/fhir/sensorkit"
    public static let sourceRecordIdentifierSystem = "https://grovealliance.org/fhir/sensorkit/NamingSystem/sensorkit-record-id"
    public static let outputIdentifierSystem = "https://grovealliance.org/fhir/sensorkit/NamingSystem/sensorkit-output-id"
    public static let outputIdentifierNamespace = "c0b8814a-8178-5e92-996a-c4cf36cd640b"
    public static let sourceTypeExtension = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-source-type"
    public static let ecgSessionGuidanceExtension = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-ecg-session-guidance"
    public static let sourceTypeCodeSystem = "https://grovealliance.org/fhir/sensorkit/CodeSystem/sensorkit-source-type"
    public static let conceptCodeSystem = "https://grovealliance.org/fhir/sensorkit/CodeSystem/sensorkit-concept"
    public static let valueCodeSystem = "https://grovealliance.org/fhir/sensorkit/CodeSystem/sensorkit-value"
    public static let ecgLeadCodeSystem = "https://grovealliance.org/fhir/sensorkit/CodeSystem/sensorkit-ecg-lead"
    public static let observationProfile = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-observation"
    public static let ecgObservationProfile = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-ecg-observation"
    public static let recordingDocumentProfile = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"
    public static let conversionProvenanceProfile = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-conversion-provenance"
    public static let sensorRecordingDocumentProfile = "https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document"
    public static let sensorConversionProvenanceProfile = "https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-conversion-provenance"
    public static let recordingFormatCodeSystem = "https://grovealliance.org/fhir/sensor/CodeSystem/grove-recording-format"
    public static let defaultRawOutputDiscriminator = "native-recording"
}


enum GroveSensorKitGenerated {
    static let catalog = SensorKitFHIRCatalog(
        schemaVersion: 1,
        version: "0.2.0",
        fhirVersion: "4.0.1",
        entries: [
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.accelerometer",
                sourceTypeCode: "accelerometer",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .accelerometer,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-accelerometer-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["grove-csv-1"],
                requirement: nil
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.acousticSettings",
                sourceTypeCode: "acoustic-settings",
                minimumIOS: "26.0",
                scope: .stableAddition,
                status: .deferred,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: [],
                rawFormats: [],
                requirement: "Version 0.2.0 publishes no reviewed output contract for this stable platform symbol."
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.ambientLightSensor",
                sourceTypeCode: "ambient-light",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["grove-csv-1"],
                requirement: "The source contains heterogeneous light fields for which version 0.2.0 does not publish a lossless component profile."
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.ambientPressure",
                sourceTypeCode: "ambient-pressure",
                minimumIOS: "15.4",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["grove-csv-1"],
                requirement: "Pressure and temperature are mixed-unit fields and must not be collapsed into one SampledData value."
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.deviceUsageReport",
                sourceTypeCode: "device-usage",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .deviceUsage,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-device-usage-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["fhir-json-1", "native-json-1"],
                requirement: nil
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.electrocardiogram",
                sourceTypeCode: "ecg",
                minimumIOS: "17.4",
                scope: .catalogBaseline,
                status: .supported,
                structuredContract: .electrocardiogram,
                structuredProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-ecg-observation", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-ecg-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["fhir-json-1", "native-json-1"],
                requirement: "All batches form one complete uniform series at the exact reported frequency, one exact lead orientation is retained, and no voltage sample is omitted. Non-uniform, incomplete, mixed-lead, or inconsistent input fails closed."
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.faceMetrics",
                sourceTypeCode: "face-metrics",
                minimumIOS: "17.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["native-json-1"],
                requirement: "Version 0.2.0 publishes no reviewed structured profile for the heterogeneous face metrics."
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.heartRate",
                sourceTypeCode: "heart-rate",
                minimumIOS: "17.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["grove-csv-1"],
                requirement: "Bare SampledData cannot preserve CMHighFrequencyHeartRateDataConfidence for each source point."
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.keyboardMetrics",
                sourceTypeCode: "keyboard-metrics",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .keyboardMetrics,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-keyboard-metrics-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["native-json-1"],
                requirement: nil
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.mediaEvents",
                sourceTypeCode: "media-events",
                minimumIOS: "16.4",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["native-json-1"],
                requirement: "Media interactions do not have a reviewed source-neutral clinical Observation representation in version 0.2.0."
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.messagesUsageReport",
                sourceTypeCode: "messages-usage",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .messagesUsage,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-messages-usage-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["native-json-1"],
                requirement: nil
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.odometer",
                sourceTypeCode: "odometer",
                minimumIOS: "17.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["grove-csv-1"],
                requirement: "Speed, slope, and motion fields are heterogeneous and are not a shared Mobile distance total."
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.onWristState",
                sourceTypeCode: "on-wrist",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .onWrist,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-on-wrist-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["fhir-json-1", "native-json-1"],
                requirement: "Use onWristDate only when onWrist is true and offWristDate only when onWrist is false; the stale opposite-state date must not bracket the current state."
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.pedometerData",
                sourceTypeCode: "pedometer",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["grove-csv-1"],
                requirement: "The composite pedometer record contains multiple aggregates and is not automatically one shared step-count result."
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.phoneUsageReport",
                sourceTypeCode: "phone-usage",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .phoneUsage,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-phone-usage-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["native-json-1"],
                requirement: nil
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.photoplethysmogram",
                sourceTypeCode: "ppg",
                minimumIOS: "17.4",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .ppg,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-ppg-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["grove-ppg-1"],
                requirement: nil
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.rotationRate",
                sourceTypeCode: "rotation-rate",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .supported,
                structuredContract: .sampledData,
                structuredProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-sampled-data-observation", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["grove-csv-1"],
                requirement: nil
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.siriSpeechMetrics",
                sourceTypeCode: "siri-speech-metrics",
                minimumIOS: "15.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["native-json-1"],
                requirement: "Speech metrics have no reviewed source-neutral clinical Observation representation in version 0.2.0."
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.sleepSessions",
                sourceTypeCode: "sleep-sessions",
                minimumIOS: "26.0",
                scope: .stableAddition,
                status: .platformExclusive,
                structuredContract: .sleepSession,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-sleep-session-observation"],
                rawProfiles: [],
                rawFormats: [],
                requirement: nil
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.telephonySpeechMetrics",
                sourceTypeCode: "telephony-speech-metrics",
                minimumIOS: "15.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["native-json-1"],
                requirement: "Speech metrics have no reviewed source-neutral clinical Observation representation in version 0.2.0."
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.visits",
                sourceTypeCode: "visits",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .visit,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-visit-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["fhir-json-1", "native-json-1"],
                requirement: "The widest arrival-start through departure-end Period is the effective interval; exact arrival and departure uncertainty windows remain separate Period components. This output does not assert a clinical Encounter or expose locationId."
            ),
            SensorKitFHIRCatalogEntry(
                sourceToken: "SRSensor.wristTemperature",
                sourceTypeCode: "wrist-temperature",
                minimumIOS: "17.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: ["grove-csv-1"],
                requirement: "A wrist-temperature session is not automatically the shared body-temperature or basal-body-temperature meaning."
            ),
        ]
    )
}
