//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

// Generated by Scripts/generate-grove-sensor-swift-contract.py. Do not edit by hand.

// swiftlint:disable all

/// The producer-side assertion that admits an opaque native sensor payload.
/// Grove consumes this value during preflight and never serializes it into FHIR.
public enum SensorRawPayloadAdmission: String, CaseIterable, Hashable, Sendable {
    /// The caller explicitly authorizes disclosure of exact opaque bytes; Grove does not inspect or sanitize them.
    case callerAuthorizedOpaquePayload = "caller-authorized-opaque-payload"
    /// The producer independently verified that the supplied bytes are sanitized.
    case verifiedSanitizedInput = "verified-sanitized-input"
}


/// Generated canonical constants for the SensorKit producer.
public enum SensorKitContract {
    public static let canonicalRoot = "https://grovealliance.org/fhir/sensorkit"
    public static let sourceTypeExtension = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-source-type"
    public static let visitLocationExtension = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-visit-location"
    public static let wristTemperatureAlgorithmVersionExtension = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-wrist-temperature-algorithm-version"
    public static let visitLocationIdentifierSystem = "https://grovealliance.org/fhir/sensorkit/NamingSystem/sensorkit-visit-location-id"
    public static let sourceTypeCodeSystem = "https://grovealliance.org/fhir/sensorkit/CodeSystem/sensorkit-source-type"
    public static let conceptCodeSystem = "https://grovealliance.org/fhir/sensorkit/CodeSystem/sensorkit-concept"
    public static let valueCodeSystem = "https://grovealliance.org/fhir/sensorkit/CodeSystem/sensorkit-value"
    public static let ecgLeadCodeSystem = "https://grovealliance.org/fhir/sensorkit/CodeSystem/sensorkit-ecg-lead"
    public static let observationProfile = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-observation"
    public static let ecgObservationProfile = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-ecg-observation"
    public static let recordingDocumentProfile = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"
    public static let conversionProvenanceProfile = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-conversion-provenance"
}


enum SensorKitGenerated {
    static let catalog = SensorKitCatalog(
        schemaVersion: 0,
        version: "0.6.0",
        fhirVersion: "4.0.1",
        entries: [
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.accelerometer",
                sourceTypeCode: "accelerometer",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .accelerometer,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-accelerometer-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.triaxialAccelerationSamples],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.acousticSettings",
                sourceTypeCode: "acoustic-settings",
                minimumIOS: "26.0",
                scope: .stableAddition,
                status: .deferred,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: [],
                rawFormats: [],
                requirement: "The Grove FHIR contracts publish no admitted output contract for this stable platform symbol."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.ambientLightSensor",
                sourceTypeCode: "ambient-light",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.ambientLightSamples],
                requirement: "The source contains heterogeneous light fields for which the Grove FHIR contracts do not publish a lossless component profile."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.ambientPressure",
                sourceTypeCode: "ambient-pressure",
                minimumIOS: "15.4",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.ambientPressureSamples],
                requirement: "Pressure and temperature are mixed-unit fields and must not be collapsed into one SampledData value."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.deviceUsageReport",
                sourceTypeCode: "device-usage",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .deviceUsage,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-device-usage-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.fhirCollectionBundle, .nativeRecording],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.electrocardiogram",
                sourceTypeCode: "ecg",
                minimumIOS: "17.4",
                scope: .catalogBaseline,
                status: .supported,
                structuredContract: .electrocardiogram,
                structuredProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-ecg-observation", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-ecg-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.fhirCollectionBundle, .nativeRecording],
                requirement: "All batches form one complete uniform series at the exact reported frequency, one exact lead orientation is retained, and no voltage sample is omitted. The duration ends at the final sample instant: final batch offset + (final batch sample count - 1) / frequency. Non-uniform, incomplete, mixed-lead, or inconsistent input fails closed."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.faceMetrics",
                sourceTypeCode: "face-metrics",
                minimumIOS: "17.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.nativeRecording],
                requirement: "The Grove FHIR contracts publish no structured profile for the heterogeneous face metrics."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.heartRate",
                sourceTypeCode: "heart-rate",
                minimumIOS: "17.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.heartRateSamples],
                requirement: "Bare SampledData cannot preserve CMHighFrequencyHeartRateDataConfidence for each source point."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.keyboardMetrics",
                sourceTypeCode: "keyboard-metrics",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .keyboardMetrics,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-keyboard-metrics-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.nativeRecording],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.mediaEvents",
                sourceTypeCode: "media-events",
                minimumIOS: "16.4",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.nativeRecording],
                requirement: "Media interactions do not have a source-neutral clinical Observation representation under the Grove FHIR contracts."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.messagesUsageReport",
                sourceTypeCode: "messages-usage",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .messagesUsage,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-messages-usage-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.nativeRecording],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.odometer",
                sourceTypeCode: "odometer",
                minimumIOS: "17.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.odometerSamples],
                requirement: "Speed, slope, and motion fields are heterogeneous and are not a shared Mobile distance total."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.onWristState",
                sourceTypeCode: "on-wrist",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .onWrist,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-on-wrist-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.fhirCollectionBundle, .nativeRecording],
                requirement: "Use onWristDate only when onWrist is true and offWristDate only when onWrist is false; the stale opposite-state date must not bracket the current state."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.pedometerData",
                sourceTypeCode: "pedometer",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.pedometerSamples],
                requirement: "The composite pedometer record contains multiple aggregates and is not automatically one shared step-count result."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.phoneUsageReport",
                sourceTypeCode: "phone-usage",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .phoneUsage,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-phone-usage-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.nativeRecording],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.photoplethysmogram",
                sourceTypeCode: "ppg",
                minimumIOS: "17.4",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .ppg,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-ppg-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.photoplethysmogramSamples],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.rotationRate",
                sourceTypeCode: "rotation-rate",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .supported,
                structuredContract: .sampledData,
                structuredProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-sampled-data-observation", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.triaxialRotationSamples],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.siriSpeechMetrics",
                sourceTypeCode: "siri-speech-metrics",
                minimumIOS: "15.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.nativeRecording],
                requirement: "Speech metrics have no source-neutral clinical Observation representation under the Grove FHIR contracts."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.sleepSessions",
                sourceTypeCode: "sleep-sessions",
                minimumIOS: "26.0",
                scope: .stableAddition,
                status: .platformExclusive,
                structuredContract: .sleepSession,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-sleep-session-observation"],
                rawProfiles: [],
                rawFormats: [],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.telephonySpeechMetrics",
                sourceTypeCode: "telephony-speech-metrics",
                minimumIOS: "15.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.nativeRecording],
                requirement: "Speech metrics have no source-neutral clinical Observation representation under the Grove FHIR contracts."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.visits",
                sourceTypeCode: "visits",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .visit,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-visit-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.fhirCollectionBundle, .nativeRecording],
                requirement: "The widest arrival-start through departure-end Period is the effective interval; exact arrival and departure uncertainty windows remain separate Period components. This output does not assert a clinical Encounter. When SensorKit supplies locationId, preserve it exactly as Observation.focus on an identifier-only logical Location Reference under the deployment's source-store-scoped namespace; no content-empty Location resource is created."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.wristTemperature",
                sourceTypeCode: "wrist-temperature",
                minimumIOS: "17.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .wristTemperature,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-wrist-temperature-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.wristTemperatureSamples],
                requirement: "A sleep-interval wrist skin reading is neither body nor basal body temperature, so the Grove FHIR contracts publish a platform-scoped summary rather than binding it to a shared clinical meaning."
            ),
        ]
    )
}
