//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

// Generated by Scripts/generate-grove-sensor-swift-contract.py. Do not edit by hand.

// swiftlint:disable all

/// The producer-side assertion that admits an opaque native sensor payload.
/// Grove consumes this value during preflight and never serializes it into FHIR.
public enum SensorRawPayloadAdmission: String, CaseIterable, Hashable, Sendable {
    /// The caller explicitly authorizes disclosure of exact opaque bytes; Grove does not inspect or sanitize them.
    case callerAuthorizedOpaquePayload = "caller-authorized-opaque-payload"
    /// The producer independently verified that the supplied bytes are sanitized.
    case verifiedSanitizedInput = "verified-sanitized-input"
}


/// Generated canonical and identity constants for the SensorKit v0.3 producer.
public enum SensorKitContract {
    public static let canonicalRoot = "https://grovealliance.org/fhir/sensorkit"
    public static let sourceRecordIdentifierSystem = "https://grovealliance.org/fhir/sensorkit/NamingSystem/sensorkit-record-id"
    public static let outputIdentifierSystem = "https://grovealliance.org/fhir/sensorkit/NamingSystem/sensorkit-output-id"
    public static let sourceTypeExtension = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-source-type"
    public static let ecgSessionGuidanceExtension = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-ecg-session-guidance"
    public static let visitLocationExtension = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-visit-location"
    public static let wristTemperatureAlgorithmVersionExtension = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-wrist-temperature-algorithm-version"
    public static let visitLocationIdentifierSystem = "https://grovealliance.org/fhir/sensorkit/NamingSystem/sensorkit-visit-location-id"
    public static let sourceTypeCodeSystem = "https://grovealliance.org/fhir/sensorkit/CodeSystem/sensorkit-source-type"
    public static let conceptCodeSystem = "https://grovealliance.org/fhir/sensorkit/CodeSystem/sensorkit-concept"
    public static let valueCodeSystem = "https://grovealliance.org/fhir/sensorkit/CodeSystem/sensorkit-value"
    public static let ecgLeadCodeSystem = "https://grovealliance.org/fhir/sensorkit/CodeSystem/sensorkit-ecg-lead"
    public static let observationProfile = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-observation"
    public static let ecgObservationProfile = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-ecg-observation"
    public static let recordingDocumentProfile = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"
    public static let conversionProvenanceProfile = "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-conversion-provenance"
    public static let sensorRecordingDocumentProfile = "https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document"
    public static let sensorConversionProvenanceProfile = "https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-conversion-provenance"
    public static let recordingFormatCodeSystem = "https://grovealliance.org/fhir/sensor/CodeSystem/grove-recording-format"
    public static let defaultRawOutputDiscriminator = "native-recording"
}


/// A payload format published by the Grove recording-format registry.
///
/// The whole registry is projected, not only the formats this adapter admits, so the type
/// means "a registered format" everywhere it appears. Whether a particular source may carry
/// one is a separate question the catalog answers through ``SensorKitCatalogEntry/rawFormats``.
public enum RegisteredRecordingFormat: String, CaseIterable, Hashable, Sendable {
    case ambientLightSamples = "ambient-light-samples"
    case ambientPressureSamples = "ambient-pressure-samples"
    case beatIntervalSeries = "beat-interval-series"
    case clinicalDocument = "clinical-document"
    case fhirResource = "fhir-resource"
    case fhirResourceArray = "fhir-resource-array"
    case heartRateSamples = "heart-rate-samples"
    case locationTrackSamples = "location-track-samples"
    case nativeRecording = "native-recording"
    case odometerSamples = "odometer-samples"
    case pedometerSamples = "pedometer-samples"
    case photoplethysmogramSamples = "photoplethysmogram-samples"
    case providerRecording = "provider-recording"
    case triaxialAccelerationSamples = "triaxial-acceleration-samples"
    case triaxialRotationSamples = "triaxial-rotation-samples"
    case wristTemperatureSamples = "wrist-temperature-samples"

    /// The media type the registry publishes for this format.
    ///
    /// A recording may declare a more specific vendor subtype of it; this is the general
    /// form a receiver can always parse.
    public var registeredContentType: String {
        switch self {
        case .ambientLightSamples: "text/csv"
        case .ambientPressureSamples: "text/csv"
        case .beatIntervalSeries: "text/csv"
        case .clinicalDocument: "application/hl7-cda+xml"
        case .fhirResource: "application/fhir+json"
        case .fhirResourceArray: "application/vnd.grovealliance.fhir-array+json"
        case .heartRateSamples: "text/csv"
        case .locationTrackSamples: "text/csv"
        case .nativeRecording: "application/vnd.grovealliance.native+json"
        case .odometerSamples: "text/csv"
        case .pedometerSamples: "text/csv"
        case .photoplethysmogramSamples: "application/vnd.grovealliance.ppg"
        case .providerRecording: "application/vnd.grovealliance.provider+json"
        case .triaxialAccelerationSamples: "text/csv"
        case .triaxialRotationSamples: "text/csv"
        case .wristTemperatureSamples: "text/csv"
        }
    }
}




extension RegisteredRecordingFormat {
    /// The closed column set the registry publishes for this format, in order.
    ///
    /// A producer emits every declared column and no others; a reader requires the same
    /// header. `nil` for a format that is not tabular.
    public var csvColumns: [String]? {
        switch self {
        case .ambientLightSamples: ["timestamp", "lux", "placement", "chromacityX", "chromacityY", "device"]
        case .ambientPressureSamples: ["timestamp", "identifier", "pressure", "temperature", "device"]
        case .beatIntervalSeries: ["timestamp", "precededByGap"]
        case .heartRateSamples: ["timestamp", "value", "confidence", "device"]
        case .locationTrackSamples: ["timestamp", "latitude", "longitude", "altitude", "horizontalAccuracy", "verticalAccuracy", "speed", "speedAccuracy", "course", "courseAccuracy"]
        case .odometerSamples: ["start", "end", "gpsDate", "speed", "speedAccuracy", "slope", "maxAbsSlope", "deltaDistance", "deltaDistanceAccuracy", "deltaAltitude", "verticalAccuracy", "originDevice", "device"]
        case .pedometerSamples: ["start", "end", "steps", "distance", "floorsUp", "floorsDown", "currentPace", "currentCadence", "avgActivePace", "device"]
        case .triaxialAccelerationSamples: ["timestamp", "identifier", "x", "y", "z", "device"]
        case .triaxialRotationSamples: ["timestamp", "x", "y", "z", "device"]
        case .wristTemperatureSamples: ["timestamp", "value", "errorEstimate", "condition"]
        default: nil
        }
    }

    /// Every format the registry publishes as a tabular recording.
    public static var tabularFormats: [RegisteredRecordingFormat] {
        [.ambientLightSamples, .ambientPressureSamples, .beatIntervalSeries, .heartRateSamples, .locationTrackSamples, .odometerSamples, .pedometerSamples, .triaxialAccelerationSamples, .triaxialRotationSamples, .wristTemperatureSamples]
    }
}


enum SensorKitGenerated {
    static let catalog = SensorKitCatalog(
        schemaVersion: 1,
        version: "0.5.0",
        fhirVersion: "4.0.1",
        entries: [
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.accelerometer",
                sourceTypeCode: "accelerometer",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .accelerometer,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-accelerometer-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.triaxialAccelerationSamples],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.acousticSettings",
                sourceTypeCode: "acoustic-settings",
                minimumIOS: "26.0",
                scope: .stableAddition,
                status: .deferred,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: [],
                rawFormats: [],
                requirement: "Version 0.5.0 publishes no reviewed output contract for this stable platform symbol."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.ambientLightSensor",
                sourceTypeCode: "ambient-light",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.ambientLightSamples],
                requirement: "The source contains heterogeneous light fields for which version 0.5.0 does not publish a lossless component profile."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.ambientPressure",
                sourceTypeCode: "ambient-pressure",
                minimumIOS: "15.4",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.ambientPressureSamples],
                requirement: "Pressure and temperature are mixed-unit fields and must not be collapsed into one SampledData value."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.deviceUsageReport",
                sourceTypeCode: "device-usage",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .deviceUsage,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-device-usage-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.fhirResourceArray, .nativeRecording],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.electrocardiogram",
                sourceTypeCode: "ecg",
                minimumIOS: "17.4",
                scope: .catalogBaseline,
                status: .supported,
                structuredContract: .electrocardiogram,
                structuredProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-ecg-observation", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-ecg-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.fhirResourceArray, .nativeRecording],
                requirement: "All batches form one complete uniform series at the exact reported frequency, one exact lead orientation is retained, and no voltage sample is omitted. Non-uniform, incomplete, mixed-lead, or inconsistent input fails closed."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.faceMetrics",
                sourceTypeCode: "face-metrics",
                minimumIOS: "17.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.nativeRecording],
                requirement: "Version 0.5.0 publishes no reviewed structured profile for the heterogeneous face metrics."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.heartRate",
                sourceTypeCode: "heart-rate",
                minimumIOS: "17.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.heartRateSamples],
                requirement: "Bare SampledData cannot preserve CMHighFrequencyHeartRateDataConfidence for each source point."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.keyboardMetrics",
                sourceTypeCode: "keyboard-metrics",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .keyboardMetrics,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-keyboard-metrics-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.nativeRecording],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.mediaEvents",
                sourceTypeCode: "media-events",
                minimumIOS: "16.4",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.nativeRecording],
                requirement: "Media interactions do not have a reviewed source-neutral clinical Observation representation in version 0.5.0."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.messagesUsageReport",
                sourceTypeCode: "messages-usage",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .messagesUsage,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-messages-usage-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.nativeRecording],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.odometer",
                sourceTypeCode: "odometer",
                minimumIOS: "17.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.odometerSamples],
                requirement: "Speed, slope, and motion fields are heterogeneous and are not a shared Mobile distance total."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.onWristState",
                sourceTypeCode: "on-wrist",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .onWrist,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-on-wrist-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.fhirResourceArray, .nativeRecording],
                requirement: "Use onWristDate only when onWrist is true and offWristDate only when onWrist is false; the stale opposite-state date must not bracket the current state."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.pedometerData",
                sourceTypeCode: "pedometer",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.pedometerSamples],
                requirement: "The composite pedometer record contains multiple aggregates and is not automatically one shared step-count result."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.phoneUsageReport",
                sourceTypeCode: "phone-usage",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .phoneUsage,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-phone-usage-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.nativeRecording],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.photoplethysmogram",
                sourceTypeCode: "ppg",
                minimumIOS: "17.4",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .ppg,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-ppg-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.photoplethysmogramSamples],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.rotationRate",
                sourceTypeCode: "rotation-rate",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .supported,
                structuredContract: .sampledData,
                structuredProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-sampled-data-observation", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.triaxialRotationSamples],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.siriSpeechMetrics",
                sourceTypeCode: "siri-speech-metrics",
                minimumIOS: "15.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.nativeRecording],
                requirement: "Speech metrics have no reviewed source-neutral clinical Observation representation in version 0.5.0."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.sleepSessions",
                sourceTypeCode: "sleep-sessions",
                minimumIOS: "26.0",
                scope: .stableAddition,
                status: .platformExclusive,
                structuredContract: .sleepSession,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-sleep-session-observation"],
                rawProfiles: [],
                rawFormats: [],
                requirement: nil
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.telephonySpeechMetrics",
                sourceTypeCode: "telephony-speech-metrics",
                minimumIOS: "15.0",
                scope: .catalogBaseline,
                status: .mappedStandard,
                structuredContract: nil,
                structuredProfiles: [],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.nativeRecording],
                requirement: "Speech metrics have no reviewed source-neutral clinical Observation representation in version 0.5.0."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.visits",
                sourceTypeCode: "visits",
                minimumIOS: "14.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .visit,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-visit-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.fhirResourceArray, .nativeRecording],
                requirement: "The widest arrival-start through departure-end Period is the effective interval; exact arrival and departure uncertainty windows remain separate Period components. This output does not assert a clinical Encounter. SensorKit's locationId is emitted only under explicit disclosure authorization, as a business identifier in the sensorkit-visit-location extension, because its recurrence across visits to one place is what makes it both analytically useful and linkable."
            ),
            SensorKitCatalogEntry(
                sourceToken: "SRSensor.wristTemperature",
                sourceTypeCode: "wrist-temperature",
                minimumIOS: "17.0",
                scope: .catalogBaseline,
                status: .platformExclusive,
                structuredContract: .wristTemperature,
                structuredProfiles: ["https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-wrist-temperature-observation"],
                rawProfiles: ["https://grovealliance.org/fhir/sensor/StructureDefinition/grove-sensor-recording-document", "https://grovealliance.org/fhir/sensorkit/StructureDefinition/sensorkit-recording-document"],
                rawFormats: [.wristTemperatureSamples],
                requirement: "A sleep-interval wrist skin reading is neither body nor basal body temperature, so version 0.5.0 publishes a platform-scoped summary rather than binding it to a shared clinical meaning."
            ),
        ]
    )
}
