#!/usr/bin/env python3
#
# This source file is part of the Grove open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT

"""Generate the Swift R4 contract constants and the HealthKit source-type inventory from the grove-fhir catalogs."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


HEADER = """//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

// Generated by Scripts/generate-grove-fhir-swift-contract.py. Do not edit by hand.
// Machine-generated catalog constants and inventory rows intentionally bypass style lint.
// swiftlint:disable all

public import Foundation
public import ModelsR4

"""


def swift_name(value: str) -> str:
    words = [word for word in re.split(r"[^A-Za-z0-9]+", value) if word]
    if not words:
        raise ValueError(f"cannot derive a Swift name from {value!r}")
    first, *rest = words
    name = first.lower() + "".join(word[:1].upper() + word[1:] for word in rest)
    if name[:1].isdigit():
        name = "value" + name
    return name


def swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


HEALTHKIT_HEADER = """//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

// Generated by Scripts/generate-grove-fhir-swift-contract.py. Do not edit by hand.
// Machine-generated inventory rows intentionally bypass style lint.
// swiftlint:disable all

#if canImport(HealthKit)

public import HealthKit


"""

SOURCE_TYPE_IDENTIFIER = re.compile(r"^HK([A-Za-z]+?)Type(?:Identifier)?([A-Za-z0-9]*)$")
LEADING_ACRONYM = re.compile(r"^([A-Z]+)(?=[A-Z][a-z]|[0-9]|$)")
EQUALITY_VECTORS = re.compile(r"^(?P<corpus>\S+): (?P<formatting>[a-z0-9-]+) and (?P<lexeme>[a-z0-9-]+)$")


def healthkit_source_type_name(identifier: str) -> str:
    """`HKQuantityTypeIdentifierVO2Max` reads as `vo2Max`, `HKWorkoutTypeIdentifier` as `workout`."""
    match = SOURCE_TYPE_IDENTIFIER.match(identifier)
    if match is None:
        raise ValueError(f"cannot derive a Swift case from HealthKit identifier {identifier!r}")
    suffix = match.group(2) or match.group(1)
    acronym = LEADING_ACRONYM.match(suffix)
    if acronym:
        return acronym.group(1).lower() + suffix[acronym.end():]
    return suffix[:1].lower() + suffix[1:]


def producer_rule_lines(exchange_protocol: dict) -> list[str]:
    rows = exchange_protocol["producerDiagnostics"]
    codes = [row["code"] for row in rows]
    if len(codes) != len(set(codes)):
        raise ValueError("producer diagnostic codes must be unique")
    cases: dict[str, str] = {}
    for code in codes:
        name = swift_name(code)
        if name in cases:
            raise ValueError(f"producer diagnostics {cases[name]!r} and {code!r} generate the same Swift case")
        cases[name] = code
    severities = {row.get("severity", "error") for row in rows}
    if not severities <= {"error", "warning"}:
        raise ValueError(f"unknown producer diagnostic severity: {sorted(severities - {'error', 'warning'})}")
    lines = [
        "/// Every registered Grove producer rule, generated from exchange-protocol.json.",
        "public enum ExchangeGraphRule: String, CaseIterable, Sendable {",
    ]
    for row in rows:
        lines.append(f"    case {swift_name(row['code'])} = {swift_string(row['code'])}")
    lines.extend([
        "",
        "    /// The registry's reason, verbatim.",
        "    public var reason: String {",
        "        switch self {",
    ])
    for row in rows:
        lines.append(f"        case .{swift_name(row['code'])}:")
        lines.append(f"            {swift_string(row['reason'])}")
    lines.extend([
        "        }",
        "    }",
        "",
        "    /// A warning names what an accepted record lost; every other rule refuses the record or graph.",
        "    public var severity: ProducerDiagnostic.Severity {",
        "        switch self {",
    ])
    warnings = [row for row in rows if row.get("severity", "error") == "warning"]
    errors = [row for row in rows if row.get("severity", "error") != "warning"]
    for group, severity in ((warnings, ".warning"), (errors, ".error")):
        if not group:
            continue
        names = ", ".join(f".{swift_name(row['code'])}" for row in group)
        lines.append(f"        case {names}:")
        lines.append(f"            {severity}")
    lines.extend([
        "        }",
        "    }",
        "}",
        "",
        "",
    ])
    return lines


def study_context_lines(exchange_protocol: dict) -> list[str]:
    roles = exchange_protocol["lifecycle"]["active"]["studyContext"]["entryNodeRoles"]
    if len(roles) != len(set(roles)) or not roles:
        raise ValueError("study context entry-node roles must be a nonempty unique list")
    lines = [
        "/// The entry-node roles of a bundled study context, generated from exchange-protocol.json.",
        "public enum StudyContextEntryNodeRole: String, CaseIterable, Sendable {",
    ]
    for role in roles:
        lines.append(f"    case {swift_name(role)} = {swift_string(role)}")
    lines.extend(["}", "", ""])
    return lines


def opaque_identity_lines(exchange_protocol: dict) -> list[str]:
    opaque_identity = exchange_protocol["opaqueIdentity"]
    kinds = opaque_identity["identityKinds"]
    names = {name for kind in kinds for name in kind["components"]}
    unsigned_decimal = opaque_identity["componentRequirements"]["unsignedDecimal"]
    if not set(unsigned_decimal) <= names:
        raise ValueError(f"unsigned-decimal components {unsigned_decimal!r} are not identity components")
    lines = [
        "/// The catalog's component rules for each opaque identity kind, generated from exchange-protocol.json.",
        "extension OpaqueIdentityKind {",
        "    /// The kind's typed components, in preimage order.",
        "    var componentNames: [String] {",
        "        switch self {",
    ]
    for kind in kinds:
        if len(kind["components"]) != len(set(kind["components"])) or not kind["components"]:
            raise ValueError(f"identity kind {kind['kind']!r} must name unique components")
        lines.append(f"        case .{swift_name(kind['kind'])}:")
        lines.append(f"            [{', '.join(swift_string(name) for name in kind['components'])}]")
    lines.extend([
        "        }",
        "    }",
        "",
        "    /// The role the kind's identifiers carry in `Identifier.type`.",
        "    var identifierRole: GroveIdentifierRole {",
        "        switch self {",
    ])
    for kind in kinds:
        lines.append(f"        case .{swift_name(kind['kind'])}: .{swift_name(kind['identifierRole'])}")
    lines.extend([
        "        }",
        "    }",
        "",
        "    /// Components whose value is a canonical unsigned decimal.",
        f"    static let unsignedDecimalComponents: Set<String> = [{', '.join(swift_string(name) for name in unsigned_decimal)}]",
        "}",
        "",
        "",
    ])
    return lines


def identifier_system_forms(exchange_protocol: dict) -> dict[str, str]:
    forms = {
        "opaqueIdentitySystemForm": exchange_protocol["opaqueIdentity"]["recommendedSystemForm"],
        "eventIdentifierSystemForm": exchange_protocol["event"]["bundleIdentifier"]["recommendedSystemForm"],
        "entryNodeIdentifierSystemForm": exchange_protocol["entryIdentity"]["entryNode"]["recommendedSystemForm"],
    }
    for name, form in forms.items():
        if not form.startswith("<deployment-root>/"):
            raise ValueError(f"{name} must start with the deployment root placeholder: {form!r}")
    for placeholder in ("<identity-kind>", "<key-id>", "<epoch>"):
        if placeholder not in forms["opaqueIdentitySystemForm"]:
            raise ValueError(f"opaque identity system form lacks {placeholder}")
    return forms


def equality_vectors(exchange_protocol: dict) -> dict[str, str]:
    match = EQUALITY_VECTORS.match(exchange_protocol["payload"]["equality"]["vectors"])
    if match is None:
        raise ValueError("payload.equality.vectors must name its corpus and two events")
    return {
        "equalityVectorCorpus": match.group("corpus"),
        "equalityFormattingVector": match.group("formatting"),
        "equalityDecimalLexemeVector": match.group("lexeme"),
    }


def generate_healthkit_source_types(catalog_directory: Path) -> str:
    healthkit_catalog = load_catalog(catalog_directory / "healthkit-adapter.json")
    identifiers = [row["sourceTypeIdentifier"] for row in healthkit_catalog["rows"]]
    names: dict[str, str] = {}
    for identifier in identifiers:
        name = healthkit_source_type_name(identifier)
        if name in names:
            raise ValueError(f"HealthKit identifiers {names[name]!r} and {identifier!r} generate the same Swift case")
        names[name] = identifier
    lines = [
        HEALTHKIT_HEADER,
        "/// Every source type in the HealthKit adapter inventory, generated from healthkit-adapter.json.",
        "public enum HealthKitSourceType: String, CaseIterable, Sendable {",
    ]
    for identifier in identifiers:
        lines.append(f"    case {healthkit_source_type_name(identifier)} = {swift_string(identifier)}")
    lines.extend([
        "",
        "    /// The inventory row of a sample's type, or `nil` for a type the inventory does not list.",
        "    public init?(_ sample: HKSample) {",
        "        self.init(rawValue: sample.sampleType.identifier)",
        "    }",
        "}",
        "",
        "#endif",
        "",
    ])
    return "\n".join(lines)


def component_result_code_system(component: dict) -> str | None:
    """The guide names a component's result CodeSystem with the last segment of its bound ValueSet."""
    value_set = component.get("valueSet")
    if not component.get("resultCodes") or not value_set:
        return None
    if "/ValueSet/" not in value_set:
        raise ValueError(f"component valueSet is not a Grove canonical: {value_set!r}")
    return value_set.replace("/ValueSet/", "/CodeSystem/")


def quantity_contract_expression(quantity: dict) -> str:
    domain = quantity.get("valueDomain")
    rendered_domain = "nil"
    if domain:
        minimum = domain["minimum"]
        maximum = domain.get("maximum")
        rendered_maximum = (
            "QuantityBoundary("
            f"value: {swift_string(json.dumps(maximum['value'], allow_nan=False))}, "
            f"inclusive: {str(maximum['inclusive']).lower()})"
        ) if maximum else "nil"
        rendered_domain = (
            "QuantityValueDomain("
            "minimum: QuantityBoundary("
            f"value: {swift_string(json.dumps(minimum['value'], allow_nan=False))}, "
            f"inclusive: {str(minimum['inclusive']).lower()}), "
            f"maximum: {rendered_maximum}, "
            f"integerOnly: {str(domain['integerOnly']).lower()})"
        )
    return (
        "QuantityContract("
        f"system: {swift_string(quantity['system'])}, "
        f"code: {swift_string(quantity['code'])}, "
        f"unit: {swift_string(quantity['unit'])}, "
        f"valueDomain: {rendered_domain})"
    )


def measurement_lines(measurement: dict) -> list[str]:
    lines = [
        f"    public static let {swift_name(measurement['id'])} = MeasurementContract(",
        f"        id: {swift_string(measurement['id'])},",
        f"        profile: Profile.{swift_name(measurement['profile'])},",
    ]
    code = measurement["code"]
    display = f", display: {swift_string(code['display'])}" if code.get("display") else ""
    lines.append(
        "        code: CodingContract("
        f"system: {swift_string(code['system'])}, "
        f"code: {swift_string(code['code'])}{display}),"
    )
    required_codings = measurement.get("requiredCodings", [])
    if required_codings:
        lines.append("        requiredCodings: [")
        for required_coding in required_codings:
            required_display = (
                f", display: {swift_string(required_coding['display'])}"
                if required_coding.get("display")
                else ""
            )
            lines.append(
                "            CodingContract("
                f"system: {swift_string(required_coding['system'])}, "
                f"code: {swift_string(required_coding['code'])}{required_display}),"
            )
        lines.append("        ],")
    else:
        lines.append("        requiredCodings: [],")
    quantity = measurement.get("quantity")
    if quantity:
        lines.append(f"        quantity: {quantity_contract_expression(quantity)},")
    else:
        lines.append("        quantity: nil,")
    components = measurement.get("components", [])
    if components:
        lines.append("        components: [")
        for component in components:
            quantity = component.get("quantity")
            rendered_quantity = quantity_contract_expression(quantity) if quantity else "nil"
            rendered_result_codes = ", ".join(
                "ResultCodeContract("
                f"code: {swift_string(result_code['code'])}, "
                f"display: {swift_string(result_code['display'])})"
                for result_code in component.get("resultCodes", [])
            )
            result_code_system = component_result_code_system(component)
            lines.append(
                "            ComponentContract("
                f"id: {swift_string(component['id'])}, "
                f"system: {swift_string(component['system'])}, "
                f"code: {swift_string(component['code'])}, "
                f"quantity: {rendered_quantity}, "
                f"resultCodeSystem: "
                f"{swift_string(result_code_system) if result_code_system else 'nil'}, "
                f"resultCodes: [{rendered_result_codes}]),"
            )
        lines.append("        ],")
    else:
        lines.append("        components: [],")
    result_code_system = measurement.get("resultCodeSystem")
    lines.append(
        f"        resultCodeSystem: {swift_string(result_code_system) if result_code_system else 'nil'},"
    )
    allowed_values = measurement.get("allowedValues", [])
    if allowed_values:
        values = ", ".join(swift_string(value) for value in allowed_values)
        lines.append(f"        allowedValues: [{values}],")
    else:
        lines.append("        allowedValues: [],")
    result_codes = measurement.get("resultCodes", [])
    if result_codes:
        lines.append("        resultCodes: [")
        for result_code in result_codes:
            lines.append(
                "            ResultCodeContract("
                f"code: {swift_string(result_code['code'])}, "
                f"display: {swift_string(result_code['display'])}),"
            )
        lines.append("        ],")
    else:
        lines.append("        resultCodes: [],")
    method = measurement.get("method")
    if method:
        lines.append(
            "        method: MethodContract("
            f"code: {swift_string(method['code'])}, "
            f"display: {swift_string(method['display'])}),"
        )
    else:
        lines.append("        method: nil,")
    method_choice = measurement.get("methodChoice", [])
    if method_choice:
        values = ", ".join(swift_string(value) for value in method_choice)
        lines.append(f"        methodChoice: [{values}],")
    else:
        lines.append("        methodChoice: [],")
    effective = {
        "dateTime": "dateTime",
        "Period": "period",
        "dateTime-or-Period": "dateTimeOrPeriod",
    }.get(measurement["effective"])
    if effective is None:
        raise ValueError(
            f"measurement {measurement['id']!r} has unsupported effective choice "
            f"{measurement['effective']!r}"
        )
    lines.append(f"        effective: .{effective}")
    lines.extend(["    )", ""])
    return lines


def load_catalog(path: Path) -> dict:
    with path.open(encoding="utf-8") as file:
        value = json.load(file)
    if value.get("fhirVersion") != "4.0.1":
        raise ValueError(f"{path} is not an R4 (4.0.1) catalog")
    return value


def generate(catalog_directory: Path) -> str:
    package_graph = load_catalog(catalog_directory / "package-graph.json")
    measurement_catalog = load_catalog(catalog_directory / "measurement-catalog.json")
    profile_claims = load_catalog(catalog_directory / "profile-claims.json")
    healthkit_catalog = load_catalog(catalog_directory / "healthkit-adapter.json")
    providers_catalog = load_catalog(catalog_directory / "providers-adapter.json")
    exchange_protocol = load_catalog(catalog_directory / "exchange-protocol.json")
    versions = {
        package_graph["version"],
        measurement_catalog["version"],
        profile_claims["version"],
        healthkit_catalog["version"],
        providers_catalog["version"],
        exchange_protocol["version"],
    }
    if len(versions) != 1:
        raise ValueError("package, measurement, and profile-claim catalogs have different versions")

    # Canonical URL -> generated Profile member, so rows and claims reference the
    # constants this file already defines instead of repeating the literal.
    profile_members = {
        f"{package['canonical']}/StructureDefinition/{profile}": f"Profile.{swift_name(profile)}"
        for package in package_graph["packages"]
        for profile in package["profiles"]
    }

    def profile_reference(canonical: str) -> str:
        return profile_members.get(canonical, swift_string(canonical))

    adapter_only_claims = [
        profile_claims["healthConnectSpecimenClaim"],
        *profile_claims["healthKitPlatformExclusiveResourceClaims"],
    ]
    adapter_only_claims.sort(key=lambda claim: claim["resourceType"])
    adapter_only_types = [claim["resourceType"] for claim in adapter_only_claims]
    protocol_adapter_only_types = sorted(
        exchange_protocol["lifecycle"]["active"]["adapterOnlyOutputProfileClaims"][
            "resourceTypes"
        ]
    )
    if adapter_only_types != protocol_adapter_only_types:
        raise ValueError("adapter-only output claims disagree with exchange-protocol.json")
    if any(
        claim["cardinality"] != 1 or claim["otherProfilesAllowed"] is not False
        for claim in adapter_only_claims
    ):
        raise ValueError("adapter-only outputs must carry exactly one direct profile")

    document_claim_names = [
        "sensorRecordingDocumentClaim",
        "healthKitRecordingDocumentClaim",
        "healthKitClinicalRecordDocumentClaim",
        "sensorKitRecordingDocumentClaim",
        "providerRecordingDocumentClaim",
    ]
    document_claims = [profile_claims[name] for name in document_claim_names]
    device_claims = profile_claims["activeDeviceClaims"]
    questionnaire_response_claim = profile_claims["activeQuestionnaireResponseClaim"]

    def validate_direct_claim(claim: dict, label: str) -> None:
        profiles = claim.get("profiles")
        if not isinstance(profiles, list) or not profiles or len(profiles) != len(set(profiles)):
            raise ValueError(f"{label} must declare a nonempty unique profile mode")
        if claim["cardinality"] != len(profiles) or claim["otherProfilesAllowed"] is not False:
            raise ValueError(f"{label} must close its exact direct profile mode")

    for name, claim in zip(document_claim_names, document_claims, strict=True):
        validate_direct_claim(claim, name)
    for claim in device_claims:
        validate_direct_claim(claim, f"activeDeviceClaims.{claim['id']}")
    validate_direct_claim(questionnaire_response_claim, "activeQuestionnaireResponseClaim")

    active_entry_policy = exchange_protocol["lifecycle"]["active"]["entryResourcePolicy"]
    if active_entry_policy["containedResourcesAllowed"] is not False:
        raise ValueError("Mobile exchange must prohibit contained resources")
    if active_entry_policy["otherResourceTypesAllowed"] is not False:
        raise ValueError("Mobile exchange must close its active entry resource types")
    if active_entry_policy["supportingResourcesMustBeConnected"] is not True:
        raise ValueError("Mobile exchange supporting resources must be connected")

    measurement_profiles = [
        (
            f"https://grovealliance.org/fhir/{measurement.get('owner', 'mobile')}"
            f"/StructureDefinition/{measurement['profile']}"
        )
        for measurement in measurement_catalog["measurements"]
    ]
    shared_observation_profiles = set(measurement_profiles)
    observation_claim = profile_claims["observationAdapterClaim"]
    shared_observation_profiles.update(observation_claim.get("sharedSensorProfiles", []))
    shared_observation_profiles.update(
        claim["semanticProfile"]
        for claim in observation_claim.get("standardAdapterClaims", [])
    )
    provider_adapter_by_owner = {
        provider["measurementOwner"]: provider["observationProfile"]
        for provider in providers_catalog["providers"]
    }
    if len(provider_adapter_by_owner) != len(providers_catalog["providers"]):
        raise ValueError("provider measurement owners must be unique")
    provider_owned_semantic_adapters = {
        canonical: provider_adapter_by_owner[measurement.get("owner", "mobile")]
        for measurement, canonical in zip(
            measurement_catalog["measurements"], measurement_profiles, strict=True
        )
        if measurement.get("owner", "mobile") in provider_adapter_by_owner
    }
    single_observation_profiles = {
        *profile_claims["healthKitSingleProfileObservationClaims"]["profiles"],
        *profile_claims["healthConnectPlatformExclusiveClaims"]["profiles"],
        *profile_claims["sensorKitPlatformExclusiveClaims"]["profiles"],
    }
    hybrid_observation_profiles = profile_claims["sensorKitHybridObservationClaims"]["profiles"]
    if len(hybrid_observation_profiles) != len(set(hybrid_observation_profiles)):
        raise ValueError("SensorKit hybrid Observation profiles must be unique")

    active_provenance_profiles = [
        exchange_protocol["profiles"]["conversionProvenance"],
        *(
            claim["profile"]
            for claim in profile_claims["adapterConversionProvenanceClaims"]
        ),
    ]
    if len(active_provenance_profiles) != len(set(active_provenance_profiles)):
        raise ValueError("active conversion Provenance profiles must be unique")
    retraction_provenance_profiles = [exchange_protocol["profiles"]["retractionProvenance"]]

    quantity_claims = []
    for measurement, canonical in zip(
        measurement_catalog["measurements"], measurement_profiles, strict=True
    ):
        quantity = measurement.get("quantity")
        if quantity is not None:
            quantity_claims.append((canonical, measurement["id"], quantity))
    quantity_claims.sort(key=lambda claim: claim[0])

    lines = [HEADER]
    lines.extend([
        "/// Canonical root of the grove-fhir package closure used to generate these constants.",
        "public enum ContractVersion {",
        f"    public static let canonicalRoot = {swift_string(package_graph['canonicalRoot'])}",
        "}",
        "",
        "",
        "/// Canonical profile URLs from the exact grove-fhir package graph.",
        "public enum Profile {",
    ])
    for package in package_graph["packages"]:
        lines.append(f"    // MARK: {package['source']}")
        for profile in package["profiles"]:
            canonical = f"{package['canonical']}/StructureDefinition/{profile}"
            lines.append(
                f"    public static let {swift_name(profile)}: FHIRPrimitive<Canonical> = {swift_string(canonical)}"
            )
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.extend(["}", "", ""])

    lines.extend([
        "/// Effective datatype fixed by a shared mobile measurement profile.",
        "public enum MeasurementEffective: String, Sendable {",
        "    case dateTime",
        "    case period = \"Period\"",
        "    case dateTimeOrPeriod = \"dateTime-or-Period\"",
        "}",
        "",
        "",
        "/// One quantity or component constraint from the generated measurement catalog.",
        "public struct QuantityBoundary: Hashable, Sendable {",
        "    public let value: Decimal",
        "    public let inclusive: Bool",
        "",
        "    init(value lexical: String, inclusive: Bool) {",
        "        guard let value = Decimal(",
        "            string: lexical,",
        "            locale: Locale(identifier: \"en_US_POSIX\")",
        "        ) else {",
        "            preconditionFailure(\"Generated quantity boundary is not a decimal: \\(lexical)\")",
        "        }",
        "        self.value = value",
        "        self.inclusive = inclusive",
        "    }",
        "}",
        "",
        "",
        "/// Closed numeric domain declared by one quantity contract.",
        "public struct QuantityValueDomain: Hashable, Sendable {",
        "    public let minimum: QuantityBoundary",
        "    public let maximum: QuantityBoundary?",
        "    public let integerOnly: Bool",
        "",
        "    public func contains(_ value: Decimal) -> Bool {",
        "        var source = value",
        "        var integer = Decimal()",
        "        NSDecimalRound(&integer, &source, 0, .plain)",
        "        guard !value.isNaN, !integerOnly || integer == value else {",
        "            return false",
        "        }",
        "        let satisfiesMinimum = minimum.inclusive ? value >= minimum.value : value > minimum.value",
        "        guard satisfiesMinimum else {",
        "            return false",
        "        }",
        "        guard let maximum else {",
        "            return true",
        "        }",
        "        return maximum.inclusive ? value <= maximum.value : value < maximum.value",
        "    }",
        "}",
        "",
        "",
        "/// One quantity or component constraint from the generated measurement catalog.",
        "public struct QuantityContract: Hashable, Sendable {",
        "    public let system: String",
        "    public let code: String",
        "    public let unit: String",
        "    public let valueDomain: QuantityValueDomain?",
        "",
        "    public init(",
        "        system: String,",
        "        code: String,",
        "        unit: String,",
        "        valueDomain: QuantityValueDomain? = nil",
        "    ) {",
        "        self.system = system",
        "        self.code = code",
        "        self.unit = unit",
        "        self.valueDomain = valueDomain",
        "    }",
        "}",
        "",
        "",
        "/// One fixed measurement code from the generated measurement catalog.",
        "public struct CodingContract: Hashable, Sendable {",
        "    public let system: String",
        "    public let code: String",
        "    public let display: String?",
        "",
        "    public init(system: String, code: String, display: String? = nil) {",
        "        self.system = system",
        "        self.code = code",
        "        self.display = display",
        "    }",
        "}",
        "",
        "",
        "/// One fixed component constraint from a shared measurement profile.",
        "public struct ComponentContract: Hashable, Sendable {",
        "    public let id: String",
        "    public let system: String",
        "    public let code: String",
        "    public let quantity: QuantityContract?",
        "    public let resultCodeSystem: String?",
        "    public let resultCodes: [ResultCodeContract]",
        "}",
        "",
        "",
        "/// One fixed aggregation-method coding asserted by a windowed measurement profile.",
        "public struct MethodContract: Hashable, Sendable {",
        "    public let code: String",
        "    public let display: String",
        "}",
        "",
        "",
        "/// One admitted coded result from a measurement's closed result value set.",
        "public struct ResultCodeContract: Hashable, Sendable {",
        "    public let code: String",
        "    public let display: String",
        "}",
        "",
        "",
        "/// One generated shared mobile measurement contract.",
        "public struct MeasurementContract: Sendable {",
        "    public let id: String",
        "    public let profile: FHIRPrimitive<Canonical>",
        "    public let code: CodingContract",
        "    public let requiredCodings: [CodingContract]",
        "    public let quantity: QuantityContract?",
        "    public let components: [ComponentContract]",
        "    public let resultCodeSystem: String?",
        "    public let allowedValues: [String]",
        "    public let resultCodes: [ResultCodeContract]",
        "    public let method: MethodContract?",
        "    public let methodChoice: [String]",
        "    public let effective: MeasurementEffective",
        "}",
        "",
        "",
    ])
    measurements = measurement_catalog["measurements"]
    owner_catalogs = [
        (
            "MeasurementCatalog",
            "Machine-generated source of truth for the shared mobile measurement matrix.",
            [m for m in measurements if m.get("owner", "mobile") == "mobile"],
        ),
        (
            "HealthKitMeasurementCatalog",
            "Machine-generated HealthKit-exclusive measurement contracts owned by the HealthKit adapter.",
            [m for m in measurements if m.get("owner") == "healthkit"],
        ),
    ]
    for catalog_name, documentation, owned_measurements in owner_catalogs:
        lines.extend([
            f"/// {documentation}",
            f"public enum {catalog_name} {{",
        ])
        for measurement in owned_measurements:
            lines.extend(measurement_lines(measurement))
        lines.append("    public static let all: [MeasurementContract] = [")
        for measurement in owned_measurements:
            lines.append(f"        {swift_name(measurement['id'])},")
        lines.extend([
            "    ]",
            "}",
            "",
            "",
        ])
    lines.extend([
        "/// Swift producer states generated from the authoritative HealthKit adapter inventory.",
        "public enum HealthKitImplementationStatus: String, CaseIterable, Sendable {",
    ])
    healthkit_statuses = sorted({row["status"] for row in healthkit_catalog["rows"]})
    for status in healthkit_statuses:
        lines.append(f"    case {swift_name(status)} = {swift_string(status)}")
    lines.extend([
        "}",
        "",
        "",
        "/// One generated row in the authoritative HealthKit adapter inventory.",
        "public struct HealthKitContractRow: Sendable {",
        "    public let sourceTypeIdentifier: String",
        "    public let title: String",
        "    public let measurementIDs: [String]",
        "    public let profiles: [FHIRPrimitive<Canonical>]",
        "    public let implementationStatus: HealthKitImplementationStatus",
        "    public let requirement: String?",
        "}",
        "",
        "",
        "/// Machine-generated HealthKit producer contract and complete source inventory.",
        "public enum HealthKitContract {",
    ])
    source_type_extension = healthkit_catalog["sourceTypeExtension"]
    if (
        source_type_extension["valueElement"] != "valueCode"
        or source_type_extension["cardinality"] != "exactly one"
        or set(source_type_extension["contexts"])
        != {
            "Observation",
            "DocumentReference",
            "VisionPrescription",
            "MedicationAdministration",
            "MedicationStatement",
        }
    ):
        raise ValueError("HealthKit source type must be one required valueCode lineage extension")
    application_device_identity = healthkit_catalog["applicationDeviceIdentity"]
    bundle_identifier_identity = application_device_identity["bundleIdentifier"]
    if bundle_identifier_identity["cardinality"] != "1..1":
        raise ValueError("HealthKit application bundle identifier must have cardinality 1..1")
    clinical_admission = healthkit_catalog["clinicalRecordAdmission"]
    clinical_representation = clinical_admission["fhirRepresentation"]
    admitted_clinical_releases = clinical_admission["admittedFHIRReleases"]
    clinical_content_types = clinical_representation["contentTypeByRelease"]
    if (
        clinical_admission["payloadFormat"] != "fhir-resource"
        or admitted_clinical_releases != ["dstu2", "r4"]
        or clinical_admission["rejectedFHIRReleases"] != ["unknown"]
        or clinical_representation["resourceType"] != "DocumentReference"
        or clinical_content_types
        != {
            "dstu2": "application/fhir+json; fhirVersion=1.0",
            "r4": "application/fhir+json; fhirVersion=4.0",
        }
    ):
        raise ValueError(
            "HealthKit clinical-record admission must preserve exact DSTU2 or R4 in an R4 DocumentReference"
        )
    ecg_claim = healthkit_catalog["sensorAdapterClaims"]["electrocardiogram"]
    correlated_symptom = ecg_claim["correlatedSymptomEvidence"]
    if len(ecg_claim["profiles"]) != profile_claims["observationAdapterClaim"]["cardinality"]:
        raise ValueError("HealthKit ECG claim has the wrong direct profile cardinality")
    body_mass_index_rows = [
        row
        for row in healthkit_catalog["rows"]
        if row["sourceTypeIdentifier"] == "HKQuantityTypeIdentifierBodyMassIndex"
    ]
    if len(body_mass_index_rows) != 1 or body_mass_index_rows[0]["measurementIDs"] != ["body-mass-index"]:
        raise ValueError("HealthKit adapter must define one exact body-mass-index row")
    body_mass_index_profiles = body_mass_index_rows[0]["profiles"]
    if len(body_mass_index_profiles) != profile_claims["observationAdapterClaim"]["cardinality"]:
        raise ValueError("HealthKit body-mass-index row has the wrong direct profile cardinality")
    lines.extend([
        "    public static let catalogVersion = "
        f"{swift_string(healthkit_catalog['version'])}",
        "    public static let sourceTypeCodeSystem: FHIRPrimitive<FHIRURI> = "
        f"{swift_string(source_type_extension['valueSystem'])}",
        "    public static let sourceTypeExtension: FHIRPrimitive<FHIRURI> = "
        f"{swift_string(source_type_extension['url'])}",
        "    public static let conversionProvenanceProfile: FHIRPrimitive<Canonical> = "
        f"{profile_reference(healthkit_catalog['conversionProvenanceProfile'])}",
        "    public static let applicationDeviceProfile: FHIRPrimitive<Canonical> = "
        f"{profile_reference(application_device_identity['profile'])}",
        "    public static let appleBundleIdentifierSystem: FHIRPrimitive<FHIRURI> = "
        f"{swift_string(bundle_identifier_identity['system'])}",
        "    public static let appleBundleIdentifierTypeSystem: FHIRPrimitive<FHIRURI> = "
        f"{swift_string(bundle_identifier_identity['typeSystem'])}",
        "    public static let appleBundleIdentifierTypeCode = "
        f"{swift_string(bundle_identifier_identity['typeCode'])}",
        "    public static let clinicalRecordProfile: FHIRPrimitive<Canonical> = "
        f"{profile_reference(clinical_admission['profile'])}",
        "    public static let clinicalFHIRPayloadFormatCode = "
        f"{swift_string(clinical_admission['payloadFormat'])}",
        "    public static let admittedClinicalFHIRReleaseCodes: Set<String> = [",
    ])
    for release in admitted_clinical_releases:
        lines.append(f"        {swift_string(release)},")
    lines.extend([
        "    ]",
        "    public static let clinicalFHIRContentTypeByRelease: [String: String] = [",
    ])
    for release in admitted_clinical_releases:
        lines.append(
            f"        {swift_string(release)}: {swift_string(clinical_content_types[release])},"
        )
    lines.extend([
        "    ]",
        "    public static let electrocardiogramSourceTypeIdentifier = "
        f"{swift_string(ecg_claim['sourceTypeIdentifier'])}",
        "    public static let electrocardiogramProfiles: [FHIRPrimitive<Canonical>] = [",
    ])
    for profile in ecg_claim["profiles"]:
        lines.append(f"        {profile_reference(profile)},")
    lines.extend([
        "    ]",
        "    public static let bodyMassIndexProfiles: [FHIRPrimitive<Canonical>] = [",
    ])
    for profile in body_mass_index_profiles:
        lines.append(f"        {profile_reference(profile)},")
    lines.extend([
        "    ]",
        "",
        "    public static let rows: [HealthKitContractRow] = [",
    ])
    healthkit_rows = healthkit_catalog["rows"]
    identifiers = [row["sourceTypeIdentifier"] for row in healthkit_rows]
    if identifiers != sorted(identifiers):
        raise ValueError("HealthKit adapter rows must be sorted by sourceTypeIdentifier")
    if len(identifiers) != len(set(identifiers)):
        raise ValueError("HealthKit adapter sourceTypeIdentifier values must be unique")
    for row in healthkit_rows:
        measurement_ids = row["measurementIDs"]
        if len(measurement_ids) > 1 and len(row["profiles"]) != len(measurement_ids):
            raise ValueError(
                "Multi-measurement HealthKit rows must pair one profile per measurement: "
                f"{row['sourceTypeIdentifier']}"
            )
        lines.extend([
            "        HealthKitContractRow(",
            f"            sourceTypeIdentifier: {swift_string(row['sourceTypeIdentifier'])},",
            f"            title: {swift_string(row['title'])},",
        ])
        if measurement_ids:
            rendered_ids = ", ".join(swift_string(value) for value in measurement_ids)
            lines.append(f"            measurementIDs: [{rendered_ids}],")
        else:
            lines.append("            measurementIDs: [],")
        profiles = row["profiles"]
        if profiles:
            rendered_profiles = ", ".join(profile_reference(value) for value in profiles)
            lines.append(f"            profiles: [{rendered_profiles}],")
        else:
            lines.append("            profiles: [],")
        lines.extend([
            "            implementationStatus: ."
            f"{swift_name(row['status'])},",
            "            requirement: "
            f"{swift_string(row['requirement']) if row.get('requirement') is not None else 'nil'}",
            "        ),",
        ])
    lines.extend([
        "    ]",
        "}",
        "",
        "",
        "/// One closed direct `meta.profile` mode and the Grove identifier roles it requires.",
        "public struct DirectProfileClaim: Sendable {",
        "    public let profiles: [FHIRPrimitive<Canonical>]",
        "    public let requiredIdentifierRoles: [String]",
        "}",
        "",
        "",
        "/// The catalog-fixed quantity semantics selected by one direct measurement profile.",
        "public struct FixedMeasurementQuantityClaim: Hashable, Sendable {",
        "    public let measurementID: String",
        "    public let quantity: QuantityContract",
        "}",
        "",
        "",
        "/// Exact direct profile-claim rules generated from profile-claims.json.",
        "public enum ProfileClaims {",
        f"    public static let observationAdapterCardinality = {profile_claims['observationAdapterClaim']['cardinality']}",
        "",
        "    public static let observationAdapterProfiles: [FHIRPrimitive<Canonical>] = [",
    ])
    for profile in profile_claims["observationAdapterClaim"]["adapterProfiles"]:
        lines.append(f"        {profile_reference(profile)},")
    lines.extend([
        "    ]",
        "",
        "    public static let forbiddenExplicitProfiles: [FHIRPrimitive<Canonical>] = [",
    ])
    for profile in profile_claims["observationAdapterClaim"]["forbiddenExplicitProfiles"]:
        lines.append(f"        {profile_reference(profile)},")
    lines.extend([
        "    ]",
        "",
        "    /// Exact one-profile claims for active output types that have no shared mobile shape.",
        "    public static let adapterOnlyOutputProfiles: [String: FHIRPrimitive<Canonical>] = [",
    ])
    for claim in adapter_only_claims:
        lines.append(
            f"        {swift_string(claim['resourceType'])}: "
            f"{profile_reference(claim['profile'])},"
        )
    lines.extend([
        "    ]",
        "",
        "    /// Every catalog semantic profile that may participate in shared-plus-adapter mode.",
        "    public static let sharedObservationProfiles: [FHIRPrimitive<Canonical>] = [",
    ])
    for profile in sorted(shared_observation_profiles):
        lines.append(f"        {profile_reference(profile)},")
    lines.extend([
        "    ]",
        "",
        "    /// Provider-owned semantic profile to its one required provider envelope.",
        "    public static let providerOwnedSemanticAdapters: [String: FHIRPrimitive<Canonical>] = [",
    ])
    for semantic, adapter in sorted(provider_owned_semantic_adapters.items()):
        lines.append(
            f"        {swift_string(semantic)}: {profile_reference(adapter)},"
        )
    lines.extend([
        "    ]",
        "",
        "    /// Adapter-owned Observation profiles whose complete direct claim is one profile.",
        "    public static let singleObservationProfiles: [FHIRPrimitive<Canonical>] = [",
    ])
    for profile in sorted(single_observation_profiles):
        lines.append(f"        {profile_reference(profile)},")
    lines.extend([
        "    ]",
        "",
        "    /// Multi-profile Observation modes that cannot be expressed as shared-plus-adapter.",
        "    public static let exactObservationProfileModes: [[FHIRPrimitive<Canonical>]] = [",
        "        [",
    ])
    for profile in hybrid_observation_profiles:
        lines.append(f"            {profile_reference(profile)},")
    lines.extend([
        "        ],",
        "    ]",
        "",
        "    /// Every exact active recording or clinical DocumentReference direct-profile mode.",
        "    public static let documentProfileModes: [DirectProfileClaim] = [",
    ])
    for claim in document_claims:
        lines.append("        DirectProfileClaim(")
        lines.append("            profiles: [")
        for profile in claim["profiles"]:
            lines.append(f"                {profile_reference(profile)},")
        lines.append("            ],")
        roles = ", ".join(
            swift_string(role) for role in claim.get("requiredIdentifierRoles", [])
        )
        lines.append(f"            requiredIdentifierRoles: [{roles}]")
        lines.append("        ),")
    lines.extend([
        "    ]",
        "",
        "    /// Every exact active Device direct-profile and typed-identifier mode.",
        "    public static let deviceProfileModes: [DirectProfileClaim] = [",
    ])
    for claim in device_claims:
        lines.append("        DirectProfileClaim(")
        lines.append("            profiles: [")
        for profile in claim["profiles"]:
            lines.append(f"                {profile_reference(profile)},")
        lines.append("            ],")
        roles = ", ".join(
            swift_string(role) for role in claim.get("requiredIdentifierRoles", [])
        )
        lines.append(f"            requiredIdentifierRoles: [{roles}]")
        lines.append("        ),")
    lines.extend([
        "    ]",
        "",
        "    /// The sole direct-profile mode for active QuestionnaireResponse support nodes.",
        "    public static let questionnaireResponseProfileModes: [DirectProfileClaim] = [",
        "        DirectProfileClaim(",
        "            profiles: [",
    ])
    for profile in questionnaire_response_claim["profiles"]:
        lines.append(f"                {profile_reference(profile)},")
    lines.extend([
        "            ],",
        "            requiredIdentifierRoles: []",
        "        ),",
        "    ]",
        "",
        "    /// The complete one-profile modes for active conversion Provenance.",
        "    public static let activeProvenanceProfiles: [FHIRPrimitive<Canonical>] = [",
    ])
    for profile in active_provenance_profiles:
        lines.append(f"        {profile_reference(profile)},")
    lines.extend([
        "    ]",
        "",
        "    /// The sole direct-profile mode for retraction Provenance.",
        "    public static let retractionProvenanceProfiles: [FHIRPrimitive<Canonical>] = [",
    ])
    for profile in retraction_provenance_profiles:
        lines.append(f"        {profile_reference(profile)},")
    lines.extend([
        "    ]",
        "",
        "    /// Adapter Provenance profile to every adapter output profile it may assert.",
        "    public static let adapterProvenanceTargetProfiles: [String: [FHIRPrimitive<Canonical>]] = [",
    ])
    for claim in profile_claims["adapterConversionProvenanceClaims"]:
        lines.append(f"        {swift_string(claim['profile'])}: [")
        for profile in claim["targetAdapterProfiles"]:
            lines.append(f"            {profile_reference(profile)},")
        lines.append("        ],")
    lines.extend([
        "    ]",
        "",
        "    /// Fixed system/code/domain semantics keyed by every quantity-bearing profile.",
        "    public static let fixedMeasurementQuantities: [String: FixedMeasurementQuantityClaim] = [",
    ])
    for canonical, measurement_id, quantity in quantity_claims:
        lines.append(
            f"        {swift_string(canonical)}: FixedMeasurementQuantityClaim("
            f"measurementID: {swift_string(measurement_id)}, "
            f"quantity: {quantity_contract_expression(quantity)}),"
        )
    lines.extend([
        "    ]",
        "",
        "    /// The only allowed direct claim shape for an adapter-produced measurement.",
        "    public static func observation(",
        "        sharedMeasurement: FHIRPrimitive<Canonical>,",
        "        adapter: FHIRPrimitive<Canonical>",
        "    ) -> [FHIRPrimitive<Canonical>] {",
        "        [sharedMeasurement, adapter]",
        "    }",
        "}",
        "",
        "",
    ])
    lines.extend(producer_rule_lines(exchange_protocol))
    lines.extend(study_context_lines(exchange_protocol))
    lines.extend(opaque_identity_lines(exchange_protocol))
    system_forms = identifier_system_forms(exchange_protocol)
    vectors = equality_vectors(exchange_protocol)
    lines.extend([
        "/// Frozen exchange-graph values generated from exchange-protocol.json.",
        "public enum ExchangeContract {",
        f"    public static let entryIdentifierExtension: FHIRPrimitive<FHIRURI> = {swift_string(exchange_protocol['extensions']['entryNodeKey'])}",
        f"    public static let fullURLNamespace = {swift_string(exchange_protocol['entryIdentity']['fullUrl']['namespace'])}",
    ])
    for name, value in {**system_forms, **vectors}.items():
        lines.append(f"    public static let {name} = {swift_string(value)}")
    lines.extend([
        "    public static let activeOutputResourceTypes: Set<String> = [",
    ])
    for resource_type in active_entry_policy["outputResourceTypes"]:
        lines.append(f"        {swift_string(resource_type)},")
    lines.extend([
        "    ]",
        "    public static let activeSupportingResourceTypes: Set<String> = [",
    ])
    for resource_type in active_entry_policy["supportingResourceTypes"]:
        lines.append(f"        {swift_string(resource_type)},")
    lines.extend([
        "    ]",
        "    public static let activeLifecycleResourceType = "
        f"{swift_string(active_entry_policy['lifecycleResourceType'])}",
        "    public static let containedResourcesAllowed = false",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog-directory", type=Path, required=True)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("Sources/GroveFHIRContract/Generated.swift"),
    )
    parser.add_argument(
        "--healthkit-output",
        type=Path,
        default=Path("Sources/GroveHealthKitFHIR/HealthKitSourceType.swift"),
    )
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    outputs = {
        arguments.output: generate(arguments.catalog_directory),
        arguments.healthkit_output: generate_healthkit_source_types(arguments.catalog_directory),
    }
    if arguments.check:
        stale = [
            path for path, generated in outputs.items()
            if (path.read_text(encoding="utf-8") if path.exists() else "") != generated
        ]
        for path in stale:
            print(f"error: {path} is not synchronized with the grove-fhir catalogs", file=sys.stderr)
        return 1 if stale else 0
    for path, generated in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
