#!/usr/bin/env python3
#
# This source file is part of the Grove open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT

"""Generate Swift R4 contract constants from the grove-fhir v0.2 catalogs."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


HEADER = """//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

// Generated by Scripts/generate-grove-fhir-swift-contract.py. Do not edit by hand.
// Machine-generated catalog constants and inventory rows intentionally bypass style lint.
// swiftlint:disable all

public import ModelsR4

"""


def swift_name(value: str) -> str:
    words = [word for word in re.split(r"[^A-Za-z0-9]+", value) if word]
    if not words:
        raise ValueError(f"cannot derive a Swift name from {value!r}")
    first, *rest = words
    name = first.lower() + "".join(word[:1].upper() + word[1:] for word in rest)
    if name[:1].isdigit():
        name = "value" + name
    return name


def swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def component_result_code_system(component: dict) -> str | None:
    """The guide names a component's result CodeSystem with the last segment of its bound ValueSet."""
    value_set = component.get("valueSet")
    if not component.get("resultCodes") or not value_set:
        return None
    if "/ValueSet/" not in value_set:
        raise ValueError(f"component valueSet is not a Grove canonical: {value_set!r}")
    return value_set.replace("/ValueSet/", "/CodeSystem/")


def measurement_lines(measurement: dict) -> list[str]:
    lines = [
        f"    public static let {swift_name(measurement['id'])} = GroveFHIRMeasurementContract(",
        f"        id: {swift_string(measurement['id'])},",
        f"        profile: GroveFHIRProfile.{swift_name(measurement['profile'])},",
    ]
    code = measurement["code"]
    display = f", display: {swift_string(code['display'])}" if code.get("display") else ""
    lines.append(
        "        code: GroveFHIRCodingContract("
        f"system: {swift_string(code['system'])}, "
        f"code: {swift_string(code['code'])}{display}),"
    )
    quantity = measurement.get("quantity")
    if quantity:
        lines.append(
            "        quantity: GroveFHIRQuantityContract("
            f"system: {swift_string(quantity['system'])}, "
            f"code: {swift_string(quantity['code'])}, "
            f"unit: {swift_string(quantity['unit'])}),"
        )
    else:
        lines.append("        quantity: nil,")
    components = measurement.get("components", [])
    if components:
        lines.append("        components: [")
        for component in components:
            quantity = component.get("quantity")
            rendered_quantity = (
                "GroveFHIRQuantityContract("
                f"system: {swift_string(quantity['system'])}, "
                f"code: {swift_string(quantity['code'])}, "
                f"unit: {swift_string(quantity['unit'])})"
            ) if quantity else "nil"
            rendered_result_codes = ", ".join(
                "GroveFHIRResultCodeContract("
                f"code: {swift_string(result_code['code'])}, "
                f"display: {swift_string(result_code['display'])})"
                for result_code in component.get("resultCodes", [])
            )
            result_code_system = component_result_code_system(component)
            lines.append(
                "            GroveFHIRComponentContract("
                f"id: {swift_string(component['id'])}, "
                f"system: {swift_string(component['system'])}, "
                f"code: {swift_string(component['code'])}, "
                f"quantity: {rendered_quantity}, "
                f"resultCodeSystem: "
                f"{swift_string(result_code_system) if result_code_system else 'nil'}, "
                f"resultCodes: [{rendered_result_codes}]),"
            )
        lines.append("        ],")
    else:
        lines.append("        components: [],")
    result_code_system = measurement.get("resultCodeSystem")
    lines.append(
        f"        resultCodeSystem: {swift_string(result_code_system) if result_code_system else 'nil'},"
    )
    allowed_values = measurement.get("allowedValues", [])
    if allowed_values:
        values = ", ".join(swift_string(value) for value in allowed_values)
        lines.append(f"        allowedValues: [{values}],")
    else:
        lines.append("        allowedValues: [],")
    result_codes = measurement.get("resultCodes", [])
    if result_codes:
        lines.append("        resultCodes: [")
        for result_code in result_codes:
            lines.append(
                "            GroveFHIRResultCodeContract("
                f"code: {swift_string(result_code['code'])}, "
                f"display: {swift_string(result_code['display'])}),"
            )
        lines.append("        ],")
    else:
        lines.append("        resultCodes: [],")
    method = measurement.get("method")
    if method:
        lines.append(
            "        method: GroveFHIRMethodContract("
            f"code: {swift_string(method['code'])}, "
            f"display: {swift_string(method['display'])}),"
        )
    else:
        lines.append("        method: nil,")
    method_choice = measurement.get("methodChoice", [])
    if method_choice:
        values = ", ".join(swift_string(value) for value in method_choice)
        lines.append(f"        methodChoice: [{values}],")
    else:
        lines.append("        methodChoice: [],")
    effective = "dateTime" if measurement["effective"] == "dateTime" else "period"
    lines.append(f"        effective: .{effective}")
    lines.extend(["    )", ""])
    return lines


def load_catalog(path: Path) -> dict:
    with path.open(encoding="utf-8") as file:
        value = json.load(file)
    if value.get("fhirVersion") != "4.0.1":
        raise ValueError(f"{path} is not an R4 (4.0.1) catalog")
    return value


def generate(catalog_directory: Path) -> str:
    package_graph = load_catalog(catalog_directory / "package-graph.json")
    measurement_catalog = load_catalog(catalog_directory / "measurement-catalog.json")
    profile_claims = load_catalog(catalog_directory / "profile-claims.json")
    healthkit_catalog = load_catalog(catalog_directory / "healthkit-adapter.json")
    identity = json.loads((catalog_directory / "exchange-identity.json").read_text(encoding="utf-8"))
    versions = {
        package_graph["version"],
        measurement_catalog["version"],
        profile_claims["version"],
        healthkit_catalog["version"],
        identity["version"],
    }
    if len(versions) != 1:
        raise ValueError("package, measurement, and profile-claim catalogs have different versions")

    # Canonical URL -> generated GroveFHIRProfile member, so rows and claims reference the
    # constants this file already defines instead of repeating the literal.
    profile_members = {
        f"{package['canonical']}/StructureDefinition/{profile}": f"GroveFHIRProfile.{swift_name(profile)}"
        for package in package_graph["packages"]
        for profile in package["profiles"]
    }

    def profile_reference(canonical: str) -> str:
        return profile_members.get(canonical, swift_string(canonical))

    lines = [HEADER]
    lines.extend([
        "/// Canonical root of the grove-fhir package closure used to generate these constants.",
        "public enum GroveFHIRContractVersion {",
        f"    public static let canonicalRoot = {swift_string(package_graph['canonicalRoot'])}",
        "}",
        "",
        "",
        "/// Canonical profile URLs from the exact grove-fhir package graph.",
        "public enum GroveFHIRProfile {",
    ])
    for package in package_graph["packages"]:
        lines.append(f"    // MARK: {package['source']}")
        for profile in package["profiles"]:
            canonical = f"{package['canonical']}/StructureDefinition/{profile}"
            lines.append(
                f"    public static let {swift_name(profile)}: FHIRPrimitive<Canonical> = {swift_string(canonical)}"
            )
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.extend(["}", "", ""])

    lines.extend([
        "/// Effective datatype fixed by a shared mobile measurement profile.",
        "public enum GroveFHIRMeasurementEffective: String, Sendable {",
        "    case dateTime",
        "    case period = \"Period\"",
        "}",
        "",
        "",
        "/// One quantity or component constraint from the generated measurement catalog.",
        "public struct GroveFHIRQuantityContract: Hashable, Sendable {",
        "    public let system: String",
        "    public let code: String",
        "    public let unit: String",
        "",
        "    public init(system: String, code: String, unit: String) {",
        "        self.system = system",
        "        self.code = code",
        "        self.unit = unit",
        "    }",
        "}",
        "",
        "",
        "/// One fixed measurement code from the generated measurement catalog.",
        "public struct GroveFHIRCodingContract: Hashable, Sendable {",
        "    public let system: String",
        "    public let code: String",
        "    public let display: String?",
        "",
        "    public init(system: String, code: String, display: String? = nil) {",
        "        self.system = system",
        "        self.code = code",
        "        self.display = display",
        "    }",
        "}",
        "",
        "",
        "/// One fixed component constraint from a shared measurement profile.",
        "public struct GroveFHIRComponentContract: Hashable, Sendable {",
        "    public let id: String",
        "    public let system: String",
        "    public let code: String",
        "    public let quantity: GroveFHIRQuantityContract?",
        "    public let resultCodeSystem: String?",
        "    public let resultCodes: [GroveFHIRResultCodeContract]",
        "}",
        "",
        "",
        "/// One fixed aggregation-method coding asserted by a windowed measurement profile.",
        "public struct GroveFHIRMethodContract: Hashable, Sendable {",
        "    public let code: String",
        "    public let display: String",
        "}",
        "",
        "",
        "/// One admitted coded result from a measurement's closed result value set.",
        "public struct GroveFHIRResultCodeContract: Hashable, Sendable {",
        "    public let code: String",
        "    public let display: String",
        "}",
        "",
        "",
        "/// One generated shared mobile measurement contract.",
        "public struct GroveFHIRMeasurementContract: Sendable {",
        "    public let id: String",
        "    public let profile: FHIRPrimitive<Canonical>",
        "    public let code: GroveFHIRCodingContract",
        "    public let quantity: GroveFHIRQuantityContract?",
        "    public let components: [GroveFHIRComponentContract]",
        "    public let resultCodeSystem: String?",
        "    public let allowedValues: [String]",
        "    public let resultCodes: [GroveFHIRResultCodeContract]",
        "    public let method: GroveFHIRMethodContract?",
        "    public let methodChoice: [String]",
        "    public let effective: GroveFHIRMeasurementEffective",
        "}",
        "",
        "",
    ])
    measurements = measurement_catalog["measurements"]
    owner_catalogs = [
        (
            "GroveFHIRMeasurementCatalog",
            "Machine-generated source of truth for the shared mobile measurement matrix.",
            [m for m in measurements if m.get("owner", "mobile") == "mobile"],
        ),
        (
            "GroveFHIRHealthKitMeasurementCatalog",
            "Machine-generated HealthKit-exclusive measurement contracts owned by the HealthKit adapter.",
            [m for m in measurements if m.get("owner") == "healthkit"],
        ),
    ]
    for catalog_name, documentation, owned_measurements in owner_catalogs:
        lines.extend([
            f"/// {documentation}",
            f"public enum {catalog_name} {{",
        ])
        for measurement in owned_measurements:
            lines.extend(measurement_lines(measurement))
        lines.append("    public static let all: [GroveFHIRMeasurementContract] = [")
        for measurement in owned_measurements:
            lines.append(f"        {swift_name(measurement['id'])},")
        lines.extend([
            "    ]",
            "}",
            "",
            "",
        ])
    lines.extend([
        "/// Swift producer states generated from the authoritative HealthKit adapter inventory.",
        "public enum GroveFHIRHealthKitImplementationStatus: String, CaseIterable, Sendable {",
    ])
    healthkit_statuses = sorted({row["status"] for row in healthkit_catalog["rows"]})
    for status in healthkit_statuses:
        lines.append(f"    case {swift_name(status)} = {swift_string(status)}")
    lines.extend([
        "}",
        "",
        "",
        "/// One generated row in the authoritative HealthKit adapter inventory.",
        "public struct GroveFHIRHealthKitCatalogRow: Sendable {",
        "    public let sourceTypeIdentifier: String",
        "    public let title: String",
        "    public let measurementIDs: [String]",
        "    public let profiles: [FHIRPrimitive<Canonical>]",
        "    public let implementationStatus: GroveFHIRHealthKitImplementationStatus",
        "    public let requirement: String?",
        "}",
        "",
        "",
        "/// Machine-generated HealthKit producer contract and complete source inventory.",
        "public enum GroveFHIRHealthKitCatalog {",
    ])
    source_type_coding = healthkit_catalog["sourceTypeCoding"]
    ecg_claim = healthkit_catalog["sensorAdapterClaims"]["electrocardiogram"]
    correlated_symptom = ecg_claim["correlatedSymptomEvidence"]
    if len(ecg_claim["profiles"]) != profile_claims["observationAdapterClaim"]["cardinality"]:
        raise ValueError("HealthKit ECG claim has the wrong direct profile cardinality")
    body_mass_index_rows = [
        row
        for row in healthkit_catalog["rows"]
        if row["sourceTypeIdentifier"] == "HKQuantityTypeIdentifierBodyMassIndex"
    ]
    if len(body_mass_index_rows) != 1 or body_mass_index_rows[0]["measurementIDs"] != ["body-mass-index"]:
        raise ValueError("HealthKit adapter must define one exact body-mass-index row")
    body_mass_index_profiles = body_mass_index_rows[0]["profiles"]
    if len(body_mass_index_profiles) != profile_claims["observationAdapterClaim"]["cardinality"]:
        raise ValueError("HealthKit body-mass-index row has the wrong direct profile cardinality")
    lines.extend([
        "    public static let sourceTypeCodeSystem: FHIRPrimitive<FHIRURI> = "
        f"{swift_string(source_type_coding['system'])}",
        "    public static let conversionProvenanceProfile: FHIRPrimitive<Canonical> = "
        f"{profile_reference(healthkit_catalog['conversionProvenanceProfile'])}",
        "    public static let electrocardiogramSourceTypeIdentifier = "
        f"{swift_string(ecg_claim['sourceTypeIdentifier'])}",
        "    public static let electrocardiogramProfiles: [FHIRPrimitive<Canonical>] = [",
    ])
    for profile in ecg_claim["profiles"]:
        lines.append(f"        {profile_reference(profile)},")
    lines.extend([
        "    ]",
        "    public static let bodyMassIndexProfiles: [FHIRPrimitive<Canonical>] = [",
    ])
    for profile in body_mass_index_profiles:
        lines.append(f"        {profile_reference(profile)},")
    lines.extend([
        "    ]",
        "    public static let electrocardiogramCorrelatedSymptomExtension: FHIRPrimitive<FHIRURI> = "
        f"{swift_string(correlated_symptom['url'])}",
        "",
        "    public static let rows: [GroveFHIRHealthKitCatalogRow] = [",
    ])
    healthkit_rows = healthkit_catalog["rows"]
    identifiers = [row["sourceTypeIdentifier"] for row in healthkit_rows]
    if identifiers != sorted(identifiers):
        raise ValueError("HealthKit adapter rows must be sorted by sourceTypeIdentifier")
    if len(identifiers) != len(set(identifiers)):
        raise ValueError("HealthKit adapter sourceTypeIdentifier values must be unique")
    for row in healthkit_rows:
        measurement_ids = row["measurementIDs"]
        if len(measurement_ids) > 1 and len(row["profiles"]) != len(measurement_ids):
            raise ValueError(
                "Multi-measurement HealthKit rows must pair one profile per measurement: "
                f"{row['sourceTypeIdentifier']}"
            )
        lines.extend([
            "        GroveFHIRHealthKitCatalogRow(",
            f"            sourceTypeIdentifier: {swift_string(row['sourceTypeIdentifier'])},",
            f"            title: {swift_string(row['title'])},",
        ])
        if measurement_ids:
            rendered_ids = ", ".join(swift_string(value) for value in measurement_ids)
            lines.append(f"            measurementIDs: [{rendered_ids}],")
        else:
            lines.append("            measurementIDs: [],")
        profiles = row["profiles"]
        if profiles:
            rendered_profiles = ", ".join(profile_reference(value) for value in profiles)
            lines.append(f"            profiles: [{rendered_profiles}],")
        else:
            lines.append("            profiles: [],")
        lines.extend([
            "            implementationStatus: ."
            f"{swift_name(row['status'])},",
            "            requirement: "
            f"{swift_string(row['requirement']) if row.get('requirement') is not None else 'nil'}",
            "        ),",
        ])
    lines.extend([
        "    ]",
        "}",
        "",
        "",
        "/// Exact direct profile-claim rules generated from profile-claims.json.",
        "public enum GroveFHIRProfileClaims {",
        f"    public static let observationAdapterCardinality = {profile_claims['observationAdapterClaim']['cardinality']}",
        "",
        "    public static let observationAdapterProfiles: [FHIRPrimitive<Canonical>] = [",
    ])
    for profile in profile_claims["observationAdapterClaim"]["adapterProfiles"]:
        lines.append(f"        {profile_reference(profile)},")
    lines.extend([
        "    ]",
        "",
        "    public static let forbiddenExplicitProfiles: [FHIRPrimitive<Canonical>] = [",
    ])
    for profile in profile_claims["observationAdapterClaim"]["forbiddenExplicitProfiles"]:
        lines.append(f"        {profile_reference(profile)},")
    lines.extend([
        "    ]",
        "",
        "    /// The only allowed direct claim shape for an adapter-produced measurement.",
        "    public static func observation(",
        "        sharedMeasurement: FHIRPrimitive<Canonical>,",
        "        adapter: FHIRPrimitive<Canonical>",
        "    ) -> [FHIRPrimitive<Canonical>] {",
        "        [sharedMeasurement, adapter]",
        "    }",
        "}",
        "",
        "",
        "/// Frozen exchange-graph values generated from exchange-identity.json.",
        "public enum GroveFHIRExchangeContract {",
        f"    public static let entryIdentifierExtension: FHIRPrimitive<FHIRURI> = {swift_string(identity['entryIdentifierExtension'])}",
        f"    public static let fullURLNamespace = {swift_string(identity['fullUrlAlgorithm']['namespace'])}",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog-directory", type=Path, required=True)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("Sources/GroveFHIRContract/GroveFHIRGenerated.swift"),
    )
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = generate(arguments.catalog_directory)
    if arguments.check:
        actual = arguments.output.read_text(encoding="utf-8") if arguments.output.exists() else ""
        if actual != generated:
            print(f"error: {arguments.output} is not synchronized with the grove-fhir catalogs", file=sys.stderr)
            return 1
        return 0
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
