#!/usr/bin/env python3
#
# This source file is part of the Grove open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT

"""Generate Swift Sensor/SensorKit producer contracts from the Grove FHIR catalogs."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


HEADER = """//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

// Generated by Scripts/generate-grove-sensor-swift-contract.py. Do not edit by hand.

// swiftlint:disable all
"""


def swift_name(value: str) -> str:
    words = [word for word in re.split(r"[^A-Za-z0-9]+", value) if word]
    if not words:
        raise ValueError(f"cannot derive a Swift name from {value!r}")
    first, *rest = words
    name = first.lower() + "".join(word[:1].upper() + word[1:] for word in rest)
    return "value" + name if name[:1].isdigit() else name


def swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def read_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as file:
        value = json.load(file)
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain one JSON object")
    if value.get("fhirVersion") != "4.0.1":
        raise ValueError(f"{path} is not an R4 (4.0.1) catalog")
    return value


def load_assertions(sensor: dict[str, Any]) -> list[str]:
    contracts = sensor.get("contracts")
    if not isinstance(contracts, list):
        raise ValueError("sensor catalog has no contracts array")
    matches = [contract for contract in contracts if contract.get("id") == "recording-document"]
    if len(matches) != 1:
        raise ValueError("sensor catalog must define exactly one recording-document representation")
    assertions = matches[0].get("payloadAdmission", {}).get("allowedAssertions")
    if not isinstance(assertions, list) or not assertions or not all(
        isinstance(assertion, str) and assertion for assertion in assertions
    ):
        raise ValueError("recording-document payload admission must define non-empty string assertions")
    if len(assertions) != len(set(assertions)):
        raise ValueError("recording-document payload admission assertions must be unique")
    if len({swift_name(assertion) for assertion in assertions}) != len(assertions):
        raise ValueError("recording-document payload admission assertions collide as Swift cases")
    return assertions


def structured_contract(entry: dict[str, Any]) -> str | None:
    structured = entry.get("structured")
    if not isinstance(structured, dict) or structured.get("status") == "deferred":
        return None
    return {
        "rotation-rate": "sampledData",
        "ecg": "electrocardiogram",
        "device-usage": "deviceUsage",
        "on-wrist": "onWrist",
        "visits": "visit",
        "messages-usage": "messagesUsage",
        "phone-usage": "phoneUsage",
        "keyboard-metrics": "keyboardMetrics",
        "sleep-sessions": "sleepSession",
        "accelerometer": "accelerometer",
        "ppg": "ppg",
        "wrist-temperature": "wristTemperature",
    }.get(entry["sourceTypeCode"])


def structured_profiles(entry: dict[str, Any]) -> list[str]:
    structured = entry.get("structured")
    if not isinstance(structured, dict) or structured.get("status") == "deferred":
        return []
    profiles = []
    for key in ("sourceNeutralProfile", "adapterProfile", "profile"):
        value = structured.get(key)
        if isinstance(value, str):
            profiles.append(value)
    return profiles


def raw_admitted(entry: dict[str, Any]) -> bool:
    raw = entry.get("raw")
    return isinstance(raw, dict) and raw.get("status") == "mapped-standard"


ACRONYMS = {"csv": "CSV", "ppg": "PPG", "fhir": "FHIR", "json": "JSON", "edf": "EDF"}


def swift_format_case(value: str) -> str:
    """A registry token as a Swift case name: `grove-csv-1` -> `groveCSV1`."""
    head, *rest = value.split("-")
    parts = [head.lower()]
    parts.extend(ACRONYMS.get(part, part.capitalize()) for part in rest)
    return "".join(parts)


def registered_content_types(code: str, format_contract: dict[str, Any]) -> list[str]:
    singular = format_contract.get("contentType")
    plural = format_contract.get("contentTypes")
    if isinstance(singular, str) and singular and plural is None:
        return [singular]
    if (
        singular is None
        and isinstance(plural, list)
        and plural
        and all(isinstance(value, str) and value for value in plural)
        and len(plural) == len(set(plural))
    ):
        return plural
    raise ValueError(f"registry format declares an invalid content-type set: {code}")


def raw_formats(entry: dict[str, Any]) -> list[str]:
    if not raw_admitted(entry):
        return []
    formats = entry["raw"].get("formats")
    if not isinstance(formats, list) or not formats or not all(
        isinstance(value, str) and value for value in formats
    ):
        raise ValueError(f"admitted raw row must declare registry formats: {entry['sourceToken']}")
    if len(formats) != len(set(formats)):
        raise ValueError(f"raw registry formats must be unique: {entry['sourceToken']}")
    return formats


def validate_adapter(adapter: dict[str, Any], assertions: list[str]) -> list[dict[str, Any]]:
    if adapter.get("schemaVersion") != 0 or adapter.get("packageId") != "org.grovealliance.fhir.sensorkit":
        raise ValueError("unexpected SensorKit adapter catalog identity")
    adapter_assertions = adapter.get("rawPayloadAdmission", {}).get("allowedAssertions")
    if adapter_assertions != assertions:
        raise ValueError("Sensor and SensorKit raw-payload assertions differ")
    entries = adapter.get("entries")
    if not isinstance(entries, list) or not entries:
        raise ValueError("SensorKit adapter catalog has no entries")
    tokens = [entry.get("sourceToken") for entry in entries]
    if not all(isinstance(token, str) and token for token in tokens):
        raise ValueError("SensorKit source tokens must be non-empty strings")
    if tokens != sorted(tokens):
        raise ValueError("SensorKit entries must be sorted by sourceToken")
    if len(tokens) != len(set(tokens)):
        raise ValueError("SensorKit source tokens must be unique")
    vocabulary = adapter.get("statusVocabulary")
    # The catalog states the vocabulary either as a bare list or as a status-to-definition mapping.
    if isinstance(vocabulary, dict):
        vocabulary = list(vocabulary)
    if not isinstance(vocabulary, list) or not vocabulary:
        raise ValueError("SensorKit catalog has no status vocabulary")
    for entry in entries:
        if entry.get("status") not in vocabulary:
            raise ValueError(f"unknown SensorKit status for {entry.get('sourceToken')}")
        if entry.get("status") in {"supported", "platform-exclusive"} and structured_contract(entry) is None:
            raise ValueError(f"structured SensorKit row has no known contract: {entry['sourceToken']}")
        raw_formats(entry)
    return entries


def validate_identity_contract(adapter: dict[str, Any]) -> None:
    """Require the adapter to delegate to the shared length-framed identity contract."""
    identity = adapter.get("identity")
    if not isinstance(identity, dict):
        raise ValueError("SensorKit adapter catalog has no identity contract")
    if identity.get("contract") != "catalog/exchange-protocol.json":
        raise ValueError("SensorKit identity must delegate to catalog/exchange-protocol.json")
    if identity.get("protocolVersion") != 0 or identity.get("adapterId") != "sensorkit":
        raise ValueError("SensorKit identity must use the sensorkit v0 protocol coordinates")

    expected = {
        "sourceRecord": (
            "source-record",
            [
                "adapter-id",
                "source-type",
                "repository-scope-system",
                "repository-scope-value",
                "native-record-id",
            ],
        ),
        "sourceOutput": (
            "source-output",
            [
                "adapter-id",
                "source-type",
                "repository-scope-system",
                "repository-scope-value",
                "native-record-id",
                "output-role",
                "output-discriminator",
            ],
        ),
    }
    for name, (role, components) in expected.items():
        declaration = identity.get(name)
        if not isinstance(declaration, dict):
            raise ValueError(f"SensorKit identity has no {name} declaration")
        if declaration.get("identityKind") != role or declaration.get("identifierRole") != role:
            raise ValueError(f"SensorKit {name} must use the shared {role} identity role")
        if declaration.get("components") != components:
            raise ValueError(f"SensorKit {name} component order differs from exchange protocol v0")

    artifact = identity.get("sourceArtifact")
    if not isinstance(artifact, dict):
        raise ValueError("SensorKit identity has no sourceArtifact declaration")
    if artifact.get("identityKind") != "source-artifact" or artifact.get("identifierRole") != "source-artifact":
        raise ValueError("SensorKit sourceArtifact must use the shared source-artifact identity role")


def requirement(entry: dict[str, Any]) -> str | None:
    if isinstance(entry.get("reason"), str):
        return entry["reason"]
    structured = entry.get("structured")
    if isinstance(structured, dict):
        for key in ("admissionRule", "rule", "reason"):
            if isinstance(structured.get(key), str):
                return structured[key]
    return None


def generate_registry(sensor_path: Path, registry_path: Path) -> str:
    """Project the recording-format registry itself, which every adapter shares."""
    sensor = read_json(sensor_path)
    registry = read_json(registry_path)
    sensor_canonical = sensor.get("canonical")
    if not isinstance(sensor_canonical, str) or not sensor_canonical:
        raise ValueError("sensor catalog has no canonical")
    formats = registry.get("formats")
    if not isinstance(formats, dict) or not formats:
        raise ValueError("the recording-format registry declares no formats")

    lines = [HEADER.rstrip(), ""]
    lines.extend([
        "/// Generated canonical constants for the Grove recording-format registry.",
        "public enum RecordingFormatContract {",
        f"    public static let recordingFormatCodeSystem = {swift_string(sensor_canonical + '/CodeSystem/grove-recording-format')}",
        "}",
        "",
        "",
    ])
    lines.append("/// A payload format published by the Grove recording-format registry.")
    lines.append("///")
    lines.append("/// The whole registry is projected, not only the formats one adapter admits, so the type")
    lines.append("/// means \"a registered format\" everywhere it appears. Whether a particular source may carry")
    lines.append("/// one is a separate question each adapter catalog answers.")
    lines.append("public enum RegisteredRecordingFormat: String, CaseIterable, Hashable, Sendable {")
    for value in sorted(formats):
        lines.append(f"    case {swift_format_case(value)} = {swift_string(value)}")
    lines.extend(["", "    /// The media types the registry admits for this format."])
    lines.append("    ///")
    lines.append("    /// Most formats admit one exact media type. A release-neutral format can admit several")
    lines.append("    /// versioned representations of the same payload grammar.")
    lines.append("    public var registeredContentTypes: [String] {")
    lines.append("        switch self {")
    for value in sorted(formats):
        content_types = ", ".join(
            swift_string(content_type)
            for content_type in registered_content_types(value, formats[value])
        )
        lines.append(f"        case .{swift_format_case(value)}: [{content_types}]")
    lines.extend([
        "        }",
        "    }",
        "",
        "    /// The registry's exact media type when this format has only one representation.",
        "    public var registeredContentType: String? {",
        "        registeredContentTypes.count == 1 ? registeredContentTypes[0] : nil",
        "    }",
        "}",
        "",
        "",
    ])

    # Each CSV format declares its own closed column set, so the columns hang off the format
    # itself: a reader or writer asks the code it already has instead of a parallel string table.
    csv_formats = {
        code: fmt for code, fmt in formats.items() if fmt.get("encoding") == "csv"
    }
    lines.extend([
        "extension RegisteredRecordingFormat {",
        "    /// The closed column set the registry publishes for this format, in order.",
        "    ///",
        "    /// A producer emits every declared column and no others; a reader requires the same",
        "    /// header. `nil` for a format that is not tabular.",
        "    public var csvColumns: [String]? {",
        "        switch self {",
    ])
    for code in sorted(csv_formats):
        names = ", ".join(swift_string(column["name"]) for column in csv_formats[code]["columns"])
        lines.append(f"        case .{swift_format_case(code)}: [{names}]")
    lines.extend([
        "        default: nil",
        "        }",
        "    }",
        "",
        "    /// Every format the registry publishes as a tabular recording.",
        "    public static var tabularFormats: [RegisteredRecordingFormat] {",
        "        [" + ", ".join("." + swift_format_case(code) for code in sorted(csv_formats)) + "]",
        "    }",
        "}",
        "",
    ])
    return "\n".join(lines)


def generate(sensor_path: Path, adapter_path: Path, registry_path: Path) -> str:
    sensor = read_json(sensor_path)
    adapter = read_json(adapter_path)
    registry = read_json(registry_path)
    assertions = load_assertions(sensor)
    entries = validate_adapter(adapter, assertions)
    validate_identity_contract(adapter)

    canonical = adapter["canonical"]
    sensor_canonical = sensor.get("canonical")
    if not isinstance(sensor_canonical, str) or not sensor_canonical:
        raise ValueError("sensor catalog has no canonical")
    claims = adapter["profileClaims"]
    raw_profiles = [
        claims["recordingDocument"]["sourceNeutralProfile"],
        claims["recordingDocument"]["adapterProfile"],
    ]
    lines = [HEADER.rstrip(), ""]
    lines.extend([
        "/// The producer-side assertion that admits an opaque native sensor payload.",
        "/// Grove consumes this value during preflight and never serializes it into FHIR.",
        "public enum SensorRawPayloadAdmission: String, CaseIterable, Hashable, Sendable {",
    ])
    descriptions = {
        "caller-authorized-opaque-payload": "The caller explicitly authorizes disclosure of exact opaque bytes; Grove does not inspect or sanitize them.",
        "verified-sanitized-input": "The producer independently verified that the supplied bytes are sanitized.",
    }
    for assertion in assertions:
        lines.append(f"    /// {descriptions.get(assertion, assertion)}")
        lines.append(f"    case {swift_name(assertion)} = {swift_string(assertion)}")
    lines.extend(["}", "", ""])

    constants = {
        "canonicalRoot": canonical,
        "sourceTypeExtension": f"{canonical}/StructureDefinition/sensorkit-source-type",
        "visitLocationExtension": f"{canonical}/StructureDefinition/sensorkit-visit-location",
        "wristTemperatureAlgorithmVersionExtension": f"{canonical}/StructureDefinition/sensorkit-wrist-temperature-algorithm-version",
        "visitLocationIdentifierSystem": f"{canonical}/NamingSystem/sensorkit-visit-location-id",
        "sourceTypeCodeSystem": f"{canonical}/CodeSystem/sensorkit-source-type",
        "conceptCodeSystem": f"{canonical}/CodeSystem/sensorkit-concept",
        "valueCodeSystem": f"{canonical}/CodeSystem/sensorkit-value",
        "ecgLeadCodeSystem": f"{canonical}/CodeSystem/sensorkit-ecg-lead",
        "observationProfile": claims["sharedObservation"]["adapterProfile"],
        "ecgObservationProfile": claims["hybridObservation"]["adapterProfile"],
        "recordingDocumentProfile": claims["recordingDocument"]["adapterProfile"],
        "conversionProvenanceProfile": claims["conversionProvenance"]["profile"],
    }
    lines.append("/// Generated canonical constants for the SensorKit producer.")
    lines.append("public enum SensorKitContract {")
    for name, value in constants.items():
        lines.append(f"    public static let {name} = {swift_string(value)}")
    lines.extend(["}", "", ""])

    formats = registry.get("formats")
    if not isinstance(formats, dict) or not formats:
        raise ValueError("the recording-format registry declares no formats")
    admitted = {value for entry in entries for value in raw_formats(entry)}
    unregistered = sorted(admitted - set(formats))
    if unregistered:
        raise ValueError(f"adapter admits formats outside the registry: {unregistered}")

    lines.append("enum SensorKitGenerated {")
    lines.append("    static let catalog = SensorKitCatalog(")
    lines.append(f"        schemaVersion: {adapter['schemaVersion']},")
    lines.append(f"        version: {swift_string(adapter['version'])},")
    lines.append(f"        fhirVersion: {swift_string(adapter['fhirVersion'])},")
    lines.append("        entries: [")
    status_cases = {
        "supported": "supported",
        "mapped-standard": "mappedStandard",
        "platform-exclusive": "platformExclusive",
        "unmodeled": "unmodeled",
        "deferred": "deferred",
        "intentionally-unsupported": "intentionallyUnsupported",
    }
    for entry in entries:
        profiles = structured_profiles(entry)
        raw = raw_profiles if raw_admitted(entry) else []
        contract = structured_contract(entry)
        lines.extend([
            "            SensorKitCatalogEntry(",
            f"                sourceToken: {swift_string(entry['sourceToken'])},",
            f"                sourceTypeCode: {swift_string(entry['sourceTypeCode'])},",
            f"                minimumIOS: {swift_string(entry['minimumIOS'])},",
            f"                scope: .{swift_name(entry['scope'])},",
            f"                status: .{status_cases[entry['status']]},",
            f"                structuredContract: {'.' + contract if contract else 'nil'},",
            "                structuredProfiles: [" + ", ".join(swift_string(value) for value in profiles) + "],",
            "                rawProfiles: [" + ", ".join(swift_string(value) for value in raw) + "],",
            "                rawFormats: [" + ", ".join("." + swift_format_case(value) for value in raw_formats(entry)) + "],",
            f"                requirement: {swift_string(requirement(entry)) if requirement(entry) else 'nil'}",
            "            ),",
        ])
    lines.extend(["        ]", "    )", "}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sensor-catalog", type=Path, required=True)
    parser.add_argument("--sensorkit-catalog", type=Path, required=True)
    parser.add_argument("--format-registry", type=Path, required=True)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("Sources/GroveSensorKitFHIR/SensorKitGenerated.swift"),
    )
    parser.add_argument(
        "--registry-output",
        type=Path,
        default=Path("Sources/GroveFHIRContract/RecordingFormatsGenerated.swift"),
    )
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    outputs = {
        arguments.registry_output: generate_registry(arguments.sensor_catalog, arguments.format_registry),
        arguments.output: generate(
            arguments.sensor_catalog,
            arguments.sensorkit_catalog,
            arguments.format_registry
        ),
    }
    for path, generated in outputs.items():
        if arguments.check:
            actual = path.read_text(encoding="utf-8") if path.exists() else ""
            if actual != generated:
                print(f"error: generated Swift contract {path} is stale", file=sys.stderr)
                return 1
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
