#!/usr/bin/env python3
#
# This source file is part of the Grove open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT

"""Generate typed Swift conformance fixtures from the Mobile semantic-vector corpus."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


HEADER = """//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

// Generated by Scripts/generate-grove-fhir-semantic-vector-fixtures.py. Do not edit by hand.

"""


def string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def number(value: int | float) -> str:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"semantic-vector quantity is not numeric: {value!r}")
    return json.dumps(value, allow_nan=False)


def load_vectors(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as file:
        corpus = json.load(file)
    if corpus.get("fhirVersion") != "4.0.1":
        raise ValueError(f"{path} is not an R4 (4.0.1) corpus")
    vectors = corpus.get("vectors")
    if not isinstance(vectors, list) or not vectors:
        raise ValueError("Mobile semantic-vector corpus has no vectors")
    ids = [vector.get("id") for vector in vectors if isinstance(vector, dict)]
    if len(ids) != len(vectors) or any(not isinstance(value, str) or not value for value in ids):
        raise ValueError("Mobile semantic-vector corpus contains an invalid id")
    if len(ids) != len(set(ids)):
        raise ValueError("Mobile semantic-vector ids must be unique")
    if ids != sorted(ids):
        raise ValueError("Mobile semantic vectors must be sorted by id")
    return vectors


def effective(value: dict) -> str:
    if value.get("type") == "dateTime" and isinstance(value.get("value"), str):
        return f".dateTime({string(value['value'])})"
    if (
        value.get("type") == "Period"
        and isinstance(value.get("start"), str)
        and isinstance(value.get("end"), str)
    ):
        return f".period(start: {string(value['start'])}, end: {string(value['end'])})"
    raise ValueError(f"unsupported semantic-vector effective value: {value!r}")


def result(value: dict) -> str:
    result_type = value.get("type")
    if result_type == "Quantity":
        return (
            ".quantity(value: " + number(value["value"])
            + ", system: " + string(value["system"])
            + ", code: " + string(value["code"])
            + ", unit: " + string(value["unit"]) + ")"
        )
    if result_type == "CodeableConcept":
        return (
            ".codeableConcept(system: " + string(value["system"])
            + ", code: " + string(value["code"]) + ")"
        )
    if result_type == "components":
        components = value.get("components")
        if not isinstance(components, list) or not components:
            raise ValueError("component semantic vector must have components")
        rendered = []
        for component in components:
            rendered.append(
                "                .init("
                + "id: " + string(component["id"])
                + ", system: " + string(component["system"])
                + ", code: " + string(component["code"])
                + ", value: " + number(component["value"])
                + ", quantitySystem: " + string(component["quantitySystem"])
                + ", quantityCode: " + string(component["quantityCode"])
                + ", unit: " + string(component["unit"]) + ")"
            )
        return ".components([\n" + ",\n".join(rendered) + "\n            ])"
    raise ValueError(f"unsupported semantic-vector result: {value!r}")


def generate(path: Path) -> str:
    vectors = load_vectors(path)
    lines = [HEADER.rstrip("\n"), ""]
    lines.extend([
        "struct MobileSemanticVectorFixture: Sendable {",
        "    enum Effective: Sendable {",
        "        case dateTime(String)",
        "        case period(start: String, end: String)",
        "    }",
        "",
        "    struct Component: Sendable {",
        "        let id: String",
        "        let system: String",
        "        let code: String",
        "        let value: Double",
        "        let quantitySystem: String",
        "        let quantityCode: String",
        "        let unit: String",
        "    }",
        "",
        "    enum Result: Sendable {",
        "        case quantity(value: Double, system: String, code: String, unit: String)",
        "        case components([Component])",
        "        case codeableConcept(system: String, code: String)",
        "    }",
        "",
        "    let id: String",
        "    let profile: String",
        "    let codeSystem: String",
        "    let code: String",
        "    let effective: Effective",
        "    let result: Result",
        "}",
        "",
        "",
        "enum MobileSemanticVectorFixtures {",
        "    static let all: [MobileSemanticVectorFixture] = [",
    ])
    for index, vector in enumerate(vectors):
        lines.extend([
            "        MobileSemanticVectorFixture(",
            f"            id: {string(vector['id'])},",
            f"            profile: {string(vector['profile'])},",
            f"            codeSystem: {string(vector['code']['system'])},",
            f"            code: {string(vector['code']['code'])},",
            f"            effective: {effective(vector['effective'])},",
            f"            result: {result(vector['result'])}",
            "        )," if index < len(vectors) - 1 else "        )",
        ])
    lines.extend(["    ]", "}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--corpus", type=Path, required=True)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("Tests/GroveHealthKitFHIRTests/MobileSemanticVectorFixtures.swift"),
    )
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = generate(arguments.corpus)
    if arguments.check:
        actual = arguments.output.read_text(encoding="utf-8") if arguments.output.exists() else ""
        if actual != generated:
            print(f"error: {arguments.output} is not synchronized with {arguments.corpus}", file=sys.stderr)
            return 1
        return 0
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
