#!/usr/bin/env python3
#
# This source file is part of the Grove open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT

"""Generate Swift Sensor/SensorKit producer contracts from grove-fhir v0.2 catalogs."""

from __future__ import annotations

import argparse
import json
import re
import sys
import uuid
from pathlib import Path
from typing import Any


HEADER = """//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

// Generated by Scripts/generate-grove-sensor-swift-contract.py. Do not edit by hand.

// swiftlint:disable all
"""


def swift_name(value: str) -> str:
    words = [word for word in re.split(r"[^A-Za-z0-9]+", value) if word]
    if not words:
        raise ValueError(f"cannot derive a Swift name from {value!r}")
    first, *rest = words
    name = first.lower() + "".join(word[:1].upper() + word[1:] for word in rest)
    return "value" + name if name[:1].isdigit() else name


def swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def read_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as file:
        value = json.load(file)
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain one JSON object")
    if value.get("fhirVersion") != "4.0.1":
        raise ValueError(f"{path} is not an R4 (4.0.1) catalog")
    return value


def load_assertions(sensor: dict[str, Any]) -> list[str]:
    contracts = sensor.get("contracts")
    if not isinstance(contracts, list):
        raise ValueError("sensor catalog has no contracts array")
    matches = [contract for contract in contracts if contract.get("id") == "recording-document"]
    if len(matches) != 1:
        raise ValueError("sensor catalog must define exactly one recording-document representation")
    assertions = matches[0].get("payloadAdmission", {}).get("allowedAssertions")
    if not isinstance(assertions, list) or not assertions or not all(
        isinstance(assertion, str) and assertion for assertion in assertions
    ):
        raise ValueError("recording-document payload admission must define non-empty string assertions")
    if len(assertions) != len(set(assertions)):
        raise ValueError("recording-document payload admission assertions must be unique")
    if len({swift_name(assertion) for assertion in assertions}) != len(assertions):
        raise ValueError("recording-document payload admission assertions collide as Swift cases")
    return assertions


def structured_contract(entry: dict[str, Any]) -> str | None:
    structured = entry.get("structured")
    if not isinstance(structured, dict) or structured.get("status") == "deferred":
        return None
    return {
        "rotation-rate": "sampledData",
        "ecg": "electrocardiogram",
        "device-usage": "deviceUsage",
        "on-wrist": "onWrist",
        "visits": "visit",
    }.get(entry["sourceTypeCode"])


def structured_profiles(entry: dict[str, Any]) -> list[str]:
    structured = entry.get("structured")
    if not isinstance(structured, dict) or structured.get("status") == "deferred":
        return []
    profiles = []
    for key in ("sourceNeutralProfile", "adapterProfile", "profile"):
        value = structured.get(key)
        if isinstance(value, str):
            profiles.append(value)
    return profiles


def validate_adapter(adapter: dict[str, Any], assertions: list[str]) -> list[dict[str, Any]]:
    if adapter.get("schemaVersion") != 1 or adapter.get("packageId") != "org.grovealliance.fhir.sensorkit":
        raise ValueError("unexpected SensorKit adapter catalog identity")
    adapter_assertions = adapter.get("rawPayloadAdmission", {}).get("allowedAssertions")
    if adapter_assertions != assertions:
        raise ValueError("Sensor and SensorKit raw-payload assertions differ")
    entries = adapter.get("entries")
    if not isinstance(entries, list) or not entries:
        raise ValueError("SensorKit adapter catalog has no entries")
    tokens = [entry.get("sourceToken") for entry in entries]
    if not all(isinstance(token, str) and token for token in tokens):
        raise ValueError("SensorKit source tokens must be non-empty strings")
    if tokens != sorted(tokens):
        raise ValueError("SensorKit entries must be sorted by sourceToken")
    if len(tokens) != len(set(tokens)):
        raise ValueError("SensorKit source tokens must be unique")
    vocabulary = adapter.get("statusVocabulary")
    if not isinstance(vocabulary, list):
        raise ValueError("SensorKit catalog has no status vocabulary")
    for entry in entries:
        if entry.get("status") not in vocabulary:
            raise ValueError(f"unknown SensorKit status for {entry.get('sourceToken')}")
        if entry.get("status") in {"supported", "platform-exclusive"} and structured_contract(entry) is None:
            raise ValueError(f"structured SensorKit row has no known contract: {entry['sourceToken']}")
    return entries


def validate_identity_vectors(adapter: dict[str, Any]) -> None:
    output = adapter["identity"]["output"]
    namespace = uuid.UUID(output["namespace"])
    source = adapter["identity"]["sourceRecord"]["system"]
    for vector in output["vectors"]:
        name = json.dumps(
            [source, "879d9ea2-21cb-4527-b59b-2831dc4c84ab", vector["outputDiscriminator"]],
            ensure_ascii=False,
            separators=(",", ":"),
        )
        if name != vector["canonicalPreimage"]:
            raise ValueError("SensorKit identity vector canonical preimage differs")
        if str(uuid.uuid5(namespace, name)) != vector["identifierValue"]:
            raise ValueError("SensorKit identity vector UUID differs")


def requirement(entry: dict[str, Any]) -> str | None:
    if isinstance(entry.get("reason"), str):
        return entry["reason"]
    structured = entry.get("structured")
    if isinstance(structured, dict):
        for key in ("admissionRule", "rule", "reason"):
            if isinstance(structured.get(key), str):
                return structured[key]
    return None


def generate(sensor_path: Path, adapter_path: Path) -> str:
    sensor = read_json(sensor_path)
    adapter = read_json(adapter_path)
    assertions = load_assertions(sensor)
    entries = validate_adapter(adapter, assertions)
    validate_identity_vectors(adapter)

    canonical = adapter["canonical"]
    claims = adapter["profileClaims"]
    source_system = adapter["identity"]["sourceRecord"]["system"]
    output = adapter["identity"]["output"]
    raw_profiles = [
        claims["recordingDocument"]["sourceNeutralProfile"],
        claims["recordingDocument"]["adapterProfile"],
    ]
    sensor_profiles = {
        contract["id"]: contract["profile"]
        for contract in sensor["contracts"]
        if isinstance(contract, dict) and isinstance(contract.get("profile"), str)
    }

    lines = [HEADER.rstrip(), ""]
    lines.extend([
        "/// The producer-side assertion that admits an opaque native sensor payload.",
        "/// Grove consumes this value during preflight and never serializes it into FHIR.",
        "public enum GroveSensorRawPayloadAdmission: String, CaseIterable, Hashable, Sendable {",
    ])
    descriptions = {
        "caller-authorized-opaque-payload": "The caller explicitly authorizes disclosure of exact opaque bytes; Grove does not inspect or sanitize them.",
        "verified-sanitized-input": "The producer independently verified that the supplied bytes are sanitized.",
    }
    for assertion in assertions:
        lines.append(f"    /// {descriptions.get(assertion, assertion)}")
        lines.append(f"    case {swift_name(assertion)} = {swift_string(assertion)}")
    lines.extend(["}", "", ""])

    constants = {
        "canonicalRoot": canonical,
        "sourceRecordIdentifierSystem": source_system,
        "outputIdentifierSystem": output["system"],
        "outputIdentifierNamespace": output["namespace"],
        "sourceTypeExtension": f"{canonical}/StructureDefinition/sensorkit-source-type",
        "ecgSessionGuidanceExtension": f"{canonical}/StructureDefinition/sensorkit-ecg-session-guidance",
        "sourceTypeCodeSystem": f"{canonical}/CodeSystem/sensorkit-source-type",
        "conceptCodeSystem": f"{canonical}/CodeSystem/sensorkit-concept",
        "valueCodeSystem": f"{canonical}/CodeSystem/sensorkit-value",
        "ecgLeadCodeSystem": f"{canonical}/CodeSystem/sensorkit-ecg-lead",
        "observationProfile": claims["sharedObservation"]["adapterProfile"],
        "ecgObservationProfile": claims["hybridObservation"]["adapterProfile"],
        "recordingDocumentProfile": claims["recordingDocument"]["adapterProfile"],
        "conversionProvenanceProfile": claims["conversionProvenance"]["profile"],
        "sensorRecordingDocumentProfile": claims["recordingDocument"]["sourceNeutralProfile"],
        "sensorConversionProvenanceProfile": sensor_profiles["conversion-provenance"],
        "defaultRawOutputDiscriminator": claims["recordingDocument"]["defaultOutputDiscriminator"],
    }
    lines.append("/// Generated canonical and identity constants for the SensorKit v0.2 producer.")
    lines.append("public enum GroveSensorKitContract {")
    for name, value in constants.items():
        lines.append(f"    public static let {name} = {swift_string(value)}")
    lines.extend(["}", "", ""])

    lines.append("enum GroveSensorKitGenerated {")
    lines.append("    static let catalog = SensorKitFHIRCatalog(")
    lines.append(f"        schemaVersion: {adapter['schemaVersion']},")
    lines.append(f"        version: {swift_string(adapter['version'])},")
    lines.append(f"        fhirVersion: {swift_string(adapter['fhirVersion'])},")
    lines.append("        entries: [")
    status_cases = {
        "supported": "supported",
        "mapped-standard": "mappedStandard",
        "platform-exclusive": "platformExclusive",
        "unmodeled": "unmodeled",
        "deferred": "deferred",
        "intentionally-unsupported": "intentionallyUnsupported",
    }
    for entry in entries:
        profiles = structured_profiles(entry)
        raw = raw_profiles if isinstance(entry.get("raw"), dict) and entry["raw"].get("status") == "mapped-standard" else []
        contract = structured_contract(entry)
        lines.extend([
            "            SensorKitFHIRCatalogEntry(",
            f"                sourceToken: {swift_string(entry['sourceToken'])},",
            f"                sourceTypeCode: {swift_string(entry['sourceTypeCode'])},",
            f"                minimumIOS: {swift_string(entry['minimumIOS'])},",
            f"                scope: .{swift_name(entry['scope'])},",
            f"                status: .{status_cases[entry['status']]},",
            f"                structuredContract: {'.' + contract if contract else 'nil'},",
            "                structuredProfiles: [" + ", ".join(swift_string(value) for value in profiles) + "],",
            "                rawProfiles: [" + ", ".join(swift_string(value) for value in raw) + "],",
            f"                requirement: {swift_string(requirement(entry)) if requirement(entry) else 'nil'}",
            "            ),",
        ])
    lines.extend(["        ]", "    )", "}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sensor-catalog", type=Path, required=True)
    parser.add_argument("--sensorkit-catalog", type=Path, required=True)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("Sources/GroveSensorKitFHIR/GroveSensorKitGenerated.swift"),
    )
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = generate(arguments.sensor_catalog, arguments.sensorkit_catalog)
    if arguments.check:
        actual = arguments.output.read_text(encoding="utf-8") if arguments.output.exists() else ""
        if actual != generated:
            print("error: generated SensorKit Swift contract is stale", file=sys.stderr)
            return 1
        return 0
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
