#!/bin/bash
#
# This source file is part of the Grove open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

# Dead-code analysis over the full module graph.
#
# Builds once with the compiler index store enabled for an iOS simulator destination — the only
# destination on which every module compiles (several are iOS-only and cannot build on a macOS
# host, which is also why plain `swift build` cannot feed this scan) — then points Periphery at
# the produced index. Configuration lives in .periphery.yml.
set -euo pipefail
cd "$(dirname "$0")/.."

command -v periphery > /dev/null || {
  echo "::error::periphery is not installed (brew install periphery)"; exit 1
}

export GROVE_ENABLE_DEFAULT_PACKAGE_TRAITS=1
export GROVE_EXCLUDE_DOCC_CATALOGS=1

DERIVED_DATA_PATH="${RUNNER_TEMP:+$RUNNER_TEMP/grove-periphery}"
DERIVED_DATA_PATH="${DERIVED_DATA_PATH:-$PWD/.derivedData-periphery}"

# The index store accumulates units across builds; after deleting or moving declarations, stale
# units report ghosts at their old locations. GROVE_PERIPHERY_CLEAN=1 forces a fresh index.
if [ "${GROVE_PERIPHERY_CLEAN:-0}" = "1" ]; then
  rm -rf "$DERIVED_DATA_PATH"
fi
PACKAGE_CACHE_PATH="${PACKAGE_CACHE_PATH:-${RUNNER_TEMP:-$PWD}/.packageCache}"

# xcodebuild occasionally fails to regenerate the package's autogenerated schemes ("could not
# delete old scheme"), then claims the scheme does not exist. Listing first repopulates the cache,
# and one retry covers the race.
xcodebuild -list > /dev/null 2>&1 || true
# build-for-testing, not build: the unit test targets must be in the index or every
# @testable-only reference reports as unused.
attempt() {
xcodebuild build-for-testing \
  -scheme Grove-Package \
  -destination "generic/platform=iOS Simulator" \
  -derivedDataPath "$DERIVED_DATA_PATH" \
  -packageCachePath "$PACKAGE_CACHE_PATH" \
  -skipMacroValidation -skipPackagePluginValidation \
  COMPILER_INDEX_STORE_ENABLE=YES \
  | { command -v xcbeautify > /dev/null && xcbeautify --quiet || cat; }
}
attempt || { xcodebuild -list > /dev/null 2>&1 || true; attempt; }

periphery scan \
  --index-store-path "$DERIVED_DATA_PATH/Index.noindex/DataStore" \
  --quiet \
  "$@"
