//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

// Generated by Scripts/generate-grove-sensor-swift-contract.py. Do not edit by hand.

// swiftlint:disable all

/// Generated canonical constants for the Grove recording-format registry.
public enum RecordingFormatContract {
    public static let recordingFormatCodeSystem = "https://grovealliance.org/fhir/sensor/CodeSystem/grove-recording-format"
}


/// A payload format published by the Grove recording-format registry.
///
/// The whole registry is projected, not only the formats one adapter admits, so the type
/// means "a registered format" everywhere it appears. Whether a particular source may carry
/// one is a separate question each adapter catalog answers.
public enum RegisteredRecordingFormat: String, CaseIterable, Hashable, Sendable {
    case ambientLightSamples = "ambient-light-samples"
    case ambientPressureSamples = "ambient-pressure-samples"
    case beatIntervalSeries = "beat-interval-series"
    case clinicalDocument = "clinical-document"
    case fhirCollectionBundle = "fhir-collection-bundle"
    case fhirResource = "fhir-resource"
    case heartRateSamples = "heart-rate-samples"
    case locationTrackSamples = "location-track-samples"
    case nativeRecording = "native-recording"
    case odometerSamples = "odometer-samples"
    case pedometerSamples = "pedometer-samples"
    case photoplethysmogramSamples = "photoplethysmogram-samples"
    case providerRecording = "provider-recording"
    case triaxialAccelerationSamples = "triaxial-acceleration-samples"
    case triaxialRotationSamples = "triaxial-rotation-samples"
    case wristTemperatureSamples = "wrist-temperature-samples"

    /// The media types the registry admits for this format.
    ///
    /// Most formats admit one exact media type. A release-neutral format can admit several
    /// versioned representations of the same payload grammar.
    public var registeredContentTypes: [String] {
        switch self {
        case .ambientLightSamples: ["text/csv"]
        case .ambientPressureSamples: ["text/csv"]
        case .beatIntervalSeries: ["text/csv"]
        case .clinicalDocument: ["application/hl7-cda+xml"]
        case .fhirCollectionBundle: ["application/fhir+json"]
        case .fhirResource: ["application/fhir+json; fhirVersion=1.0", "application/fhir+json; fhirVersion=4.0"]
        case .heartRateSamples: ["text/csv"]
        case .locationTrackSamples: ["text/csv"]
        case .nativeRecording: ["application/json"]
        case .odometerSamples: ["text/csv"]
        case .pedometerSamples: ["text/csv"]
        case .photoplethysmogramSamples: ["application/octet-stream"]
        case .providerRecording: ["application/json"]
        case .triaxialAccelerationSamples: ["text/csv"]
        case .triaxialRotationSamples: ["text/csv"]
        case .wristTemperatureSamples: ["text/csv"]
        }
    }

    /// The registry's exact media type when this format has only one representation.
    public var registeredContentType: String? {
        registeredContentTypes.count == 1 ? registeredContentTypes[0] : nil
    }
}


extension RegisteredRecordingFormat {
    /// The closed column set the registry publishes for this format, in order.
    ///
    /// A producer emits every declared column and no others; a reader requires the same
    /// header. `nil` for a format that is not tabular.
    public var csvColumns: [String]? {
        switch self {
        case .ambientLightSamples: ["timestamp", "lux", "placement", "chromaticityX", "chromaticityY", "device"]
        case .ambientPressureSamples: ["timestamp", "identifier", "pressure", "temperature", "device"]
        case .beatIntervalSeries: ["timestamp", "precededByGap"]
        case .heartRateSamples: ["timestamp", "value", "confidence", "device"]
        case .locationTrackSamples: ["timestamp", "latitude", "longitude", "altitude", "horizontalAccuracy", "verticalAccuracy", "speed", "speedAccuracy", "course", "courseAccuracy"]
        case .odometerSamples: ["start", "end", "gpsDate", "speed", "speedAccuracy", "slope", "maxAbsSlope", "deltaDistance", "deltaDistanceAccuracy", "deltaAltitude", "verticalAccuracy", "originDevice", "device"]
        case .pedometerSamples: ["start", "end", "steps", "distance", "floorsUp", "floorsDown", "currentPace", "currentCadence", "avgActivePace", "device"]
        case .triaxialAccelerationSamples: ["timestamp", "identifier", "x", "y", "z", "device"]
        case .triaxialRotationSamples: ["timestamp", "x", "y", "z", "device"]
        case .wristTemperatureSamples: ["timestamp", "value", "errorEstimate", "condition"]
        default: nil
        }
    }

    /// Every format the registry publishes as a tabular recording.
    public static var tabularFormats: [RegisteredRecordingFormat] {
        [.ambientLightSamples, .ambientPressureSamples, .beatIntervalSeries, .heartRateSamples, .locationTrackSamples, .odometerSamples, .pedometerSamples, .triaxialAccelerationSamples, .triaxialRotationSamples, .wristTemperatureSamples]
    }
}
